### ISSUE TITLE
Wouldn't the kerberos role fit better in the tower_utilities collection?

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/automate_tower_genie_collections#118]
As the subject says, it's solely at the OS level and IMHO doesn't really fit in the scope of this collection.

**Comment by sean-m-sullivan** [comment]
Yes, it would, I think we put it here back before we even thought of creating a utilities collection.

**Comment by ericzolf** [comment]
OK, same would then apply to tower_virtual_environments?

I can take care of both, I'll assign the issue to myself if nobody reacts.

**Comment by sean-m-sullivan** [comment]
Go for it

**Comment by ericzolf** [comment]
Aaah, we already have another Kerberos role in the tower_utilities collection...
