### ISSUE TITLE
ansible-lint fails locally and possibly in the pipeline

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/automate_tower_genie_collections#120]
I've been trying to run ansible-lint locally before I push my commits but it proved more difficult than I thought. The only way to fix the issue I could find and it's not really a solution was:

1. temporarily remove `ansible.cfg` so that it uses the standard collection directory (`ansible-galaxy collection install awx.awx` did also the trick and installed under `collections`)
2. I could get the check to work only by setting the `exclude_paths` list to _absolute_ paths in `.github/workflow-config/.ansiblelint.yml`:

```diff
-# exclude_paths:
-#  - roles/master_role_example/
+exclude_paths:
+- /home/myuser/[...development path...]/redhat_cop/tower_configuration/roles/master_role_example/
```
at the end calling then `ansible-lint -v --show-relpath -c .github/workflow-config/.ansiblelint.yml` worked.

I can live with the first point but perhaps we should document a bit somewhere how to test locally, and for the 2nd point, we could update the `.ansiblelint.yml` file to use the absolute path as in the pipeline, or is not an issue in the pipeline?

**Comment by ericzolf** [comment]
OK, the pipeline doesn't fail because the exclude is added on the command line, but we could change the config file and remove the extra exclude for easier maintenance:

```diff
diff --git a/.github/workflow-config/.ansiblelint.yml b/.github/workflow-config/.ansiblelint.yml
index 7eae186..f8da127 100644
--- a/.github/workflow-config/.ansiblelint.yml
+++ b/.github/workflow-config/.ansiblelint.yml
@@ -2,8 +2,8 @@
 # The exclude_paths does not appear to be working in pre-commit
 # this issue describes similar behavior but suggested fix doesn't work
 # https://github.com/ansible/ansible-lint/issues/371
-# exclude_paths:
-#  - roles/master_role_example/
+exclude_paths:
+- ${PWD}/roles/master_role_example/
 parseable: true
 use_default_rules: true
 # https://github.com/ansible/ansible-lint/issues/808
```

**Comment by sean-m-sullivan** [comment]
I've tried this even on Lint 4.0, right now, I'm keeping it updated in both, but right now the only one that works is the command line, so closing this issue as its beyond our control. There is only 1 maintainer to ansible-lint and I've not been able to track problems like these in the code to fix it there.
