### ISSUE TITLE
Organization / Galaxy Credential

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/automate_tower_genie_collections#123]
Are you all aware of the new requirement to associate an "Ansible Galaxy / Automation Hub API Token" credential type with an organization now in order for Tower to successfully install Roles / Collections?

https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#using-collections-in-tower

It appears there is a default "Ansible Galaxy" credential that is created when a person installs Tower.  But it needs to be associated with an Organization before projects will use it.  Without it, project sync will not install roles or collections. And I see no option for the Organization role to associate the Ansible Galaxy credentials with the Organizations that are created or updated.

**Comment by sean-m-sullivan** [comment]
I was not, but have not done much testing, sounds like it would just need to be a credential with the right parameters in credentials file.

**Comment by tonyreveal** [comment]
@sean-m-sullivan The problem isn't creating the credential.  The problem is that the credential has to be added to the Organization.   So whether you use the default "Ansible Galaxy" credential that is created when Tower is installed or you create your own credential, you still have to go to Organizations, edit your Organization, click the lookup for a Credential, and select the Galaxy/Automation Hub credential you want to associate.  That's not something that  can currently be done with the tower_configuration Organization role.

![image](https://user-images.githubusercontent.com/22101936/100762957-961bac00-33c2-11eb-91f0-2273b55e3ce6.png)

**Comment by sean-m-sullivan** [comment]
I'm Out of the office today, but let me look at the backend of this, Best solution would be to amend the organization module in the awx collection to allow for this, but then we have the chicken egg issue in terms of the settings that the credential needs to be created before the org, and what exists in a pristine tower.

**Comment by sean-m-sullivan** [comment]
So looking at this, Org can be created without one, Galaxy credential requires org while others do not, But first time a user makes it, would need to create orgs without it first. 
The org module does have a new setting of galaxy_credentials, that we need to add to the role, which it looks like you've done. We need to do a compare of the features to make sure we are up to date.

**Comment by sean-m-sullivan** [comment]
As part of this, as part of #129 and other PR's this is now resolved, Galaxy Credentials and Manifest files can now be specified.

**Comment by tonyreveal** [comment]
@sean-m-sullivan I'm not seeing updated documentation for the organizations role been to reflect how to add the Galaxy Credential after both are created.  My assumption is use organizations to create the org, use credentials to add the Galaxy credential (if not using the default) and then re-run the organizations role to update the org.  But I don't see a parameter specified for the galaxy credential in the tower_organizations spec.

**Comment by sean-m-sullivan** [comment]
You are right, the documentation for the role has not been updated, but the role task has, but the option for galaxy_credential is [here](https://github.com/redhat-cop/tower_configuration/blob/5aeb7b5cec5079a17e2efe8c18f0c8851f767df5/roles/organizations/tasks/main.yml#L9)

And it is an unfortunate chicken/egg situation that you have to add the org, add the credential, then update the org again, when doing a new galaxy credential with new org. Unfortunately there is not a way around that.
