### ISSUE TITLE
Various Fixes needed to match awx

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#124]
Here is a list of roles that need fixed and what needs added.

1. Credentials
-  update_secrets
2. Inventory Source
- enabled_var
- enabled_value
- host_filter
3. license
- change from licence to manifest
4. users
- update_secrets
5. workflows - job nodes
- identifier needs format fixed with extra space.

The following role needs to be created:
- instance_group

**Comment by sean-m-sullivan** [comment]
I've checked the other roles/modules to make sure all options match, these changes should bring us up to date.

**Comment by ericzolf** [comment]
I wanted to take a chance at the license one, but the published version of awx.awx:15.0.1 doesn't yet support the manifest format.

**Comment by tonyreveal** [comment]
Unless you've fixed it, which I don't see that you have, you also need to include a fix for updating an Organization with a Galaxy credential for  [Issue 123](https://github.com/redhat-cop/tower_configuration/issues/123)

**Comment by sean-m-sullivan** [comment]
16.0 is up on galaxy, it should be the one we are pulling when doing builds.
