### ISSUE TITLE
Deprecation warning when creating credentials

### ISSUE THREAD

**Issue by branic** [redhat-cop/automate_tower_genie_collections#126]
https://github.com/redhat-cop/tower_configuration/blob/d917601bfc076a038fbdba6d56ae11f2ed8293f2/roles/credentials/tasks/main.yml#L10

When creating credentials a deprecation warning displayed:

```
[DEPRECATION WARNING]: The kind parameter has been deprecated, please use credential_type instead. This feature will be removed in version 
ansible.tower:4.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

The credentials role needs to be updated to replace the `kind` key.

**Comment by sean-m-sullivan** [comment]
As discussed earlier, this is an depreciated option, if anyone else comes across this, please use credential_type option on your tower_config files for credentials.
