### ISSUE TITLE
Boolean variables can't be defaulted with true as 2nd parameter

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/automate_tower_genie_collections#188]
As described in https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#providing-default-values

> If you want to use the default value when variables evaluate to _false_ or an empty string you have to set the second parameter to true:

Meaning that e.g. `tower_validate_certs: false` will trigger the default in `{{ tower_validate_certs | default(omit, true) }}`, even though a value has been defined for the variable. There might be other places where this happens, but the issue became apparent based on this discussion.

**Comment by sean-m-sullivan** [comment]
Relooking at this is related to https://github.com/redhat-cop/tower_configuration/issues/132
Going to put suggestion in the PR
