### ISSUE TITLE
workflow_job_templates role always fails when state: absent

### ISSUE THREAD

**Issue by tonyreveal** [redhat-cop/automate_tower_genie_collections#207]
I had once fixed this issue, and submitted a pull request which was accepted.

The condition for task ` - name: loop over nodes in schema to add to workflow templates ` in main.yml needs to be updated so that it skips the linking of nodes if the workflow is removed:

```
when:
    - workflow_loop_var.state != "absent"
    - workflow_loop_var.simplified_workflow_nodes is defined
```

Otherwise, when ` state: absent ` the play will always fail because the workflow is removed before reaching this task.  Since the ` state ` parameter is optional and defaults to ` present ` I suggest the condition above.

**Comment by sean-m-sullivan** [comment]
This has been fixed in both legacy and Current, but will remain open till we release versions with the fix.

**Comment by djdanielsson** [comment]
I believe we should be able to close this now, @sean-m-sullivan ?
