### ISSUE TITLE
Not able to pass custom notification which is in json format

### ISSUE THREAD

**Issue by dhikrahashim** [redhat-cop/automate_tower_genie_collections#215]
@sean-m-sullivan  

  I want to pass a custom json notification like this below.

```
tower_notification:
  - name: webhook notification
    organization: OPS
    notification_type: webhook
    notification_configuration:
      url: https://webhook
        X-Custom-Header: application/json
    messages:
      success:
        body: '{
                  "@type": "MessageCard",
                  "@context": "http://schema.org/extensions",
                  "summary": "Job success: {{ job.name }}",
                  "title": "Job success: {{ job.name }}",
                  "themeColor": "11e839",
                  "sections": [
                      {
                          "title": "Details",
                          "facts": [
                              {
                                  "name": "Start date",
                                  "value": "{{ job.started }}"
                              },
                              {
                                  "name": "End date",
                                  "value": "{{ job.finished }}"
                              },
                              {
                                  "name": "Inventory",
                                  "value": "{{ job.summary_fields.inventory.name }}"
                              }
                          ]
                      }
                  ],
                  "potentialAction": [
                      {
                          "@context": "http://schema.org",
                          "@type": "ViewAction",
                          "name": "View on Ansible",
                          "target": [
                              "{{ url }}"
                          ]
                      }
                  ]
              }'
              ```

[https://github.com/redhat-cop/tower_configuration/blob/09ae24711a32219257ddb93d4ff27337a0a5b8da/playbooks/configs/notifications.yml#L18](url)

I even tried to pass custom message as json file using lookup module and got 500 internal server error

tower_notification:
  - name: webhook notification
    organization: OPS
    notification_type: webhook
    notification_configuration:
      url: https://webhook
        X-Custom-Header: application/json
    messages:
      success:
        body: "{{ lookup('file','output.json') | from_json }}"

**Comment by sean-m-sullivan** [comment]
I am not sure what the 500 error is, but best bet is to get it working in tower API, then visit the notifications API page, and copy the code from there. Tower has internal checks on the notifications, that will evaluate them. In addition for the role, it replaces double spaces to allow passing of variables like so ,{  {, referenced here: https://github.com/redhat-cop/tower_configuration/tree/devel/roles/notification_templates#variables-1

**Comment by dhikrahashim** [comment]
double space works

**Comment by dhikrahashim** [comment]
Is it possible to use a separate file for this custom messages.

```
messages:
      success:
        body: "{{ lookup('file','files/success.json') | from_json }}"
        ```

**Comment by sean-m-sullivan** [comment]
That I am not sure about due to the double space/file lookup, I know if its proper json, that works because we do it with surveys that have dynamic fields that have vars populated after file import, but before the role task, but because the "var" {{ body }}, is not defined at the time it may need to be a string in json ' ', with the double quotes.

**Comment by sean-m-sullivan** [comment]
Since we have found that it is not the role causing this but tower API limitations, I am closing this issue, If you feel this is wrong or have more questions, please feel free to reopen the issue.
