### ISSUE TITLE
Add when clause to all roles

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#218]
Add when clause to all roles

```
- when: tower_job_templates is defined
  name: Add Ansible Tower Job Template
```
That enables users to have playbooks which create say 10 different types of resource but if 2 are missing it will just work?

**Comment by ericzolf** [comment]
I prefer to have the roles looping over variables which are an empty list by default, it removes many useless skips.

```yaml
tower_job_templates: []  # in defaults/main.yml
```
or
```yaml
loop: "{{ tower_job_templates | default([]) }}"  # in tasks/main.yml
```

I personally prefer the first approach.

**Comment by sean-m-sullivan** [comment]
That works as well, the idea was just brought up in a chat, and thought the ability to use one playbook that can support multiple deployments depending on what is defined, was the end goal

**Comment by ericzolf** [comment]
Well, the result is the same, isn't it? It's just that it looks nicer with empty lists as default.

**Comment by sean-m-sullivan** [comment]
Sorry, Was more agreeing with you, and giving background on the idea, I like your 2nd solution the most, as it just works, without messing with defaults in the role.

**Comment by Tompage1994** [comment]
I'm pretty sure this functionality already exists as 

```
tower_job_templates: []  # in defaults/main.yml
```

is already present in defaults for most (if not all) roles

**Comment by sean-m-sullivan** [comment]
Double checked all the files, Tom is right, closing
