### ISSUE TITLE
feature, remove old content

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/automate_tower_genie_collections#239]
Some people may want the ability to remove old content that is no longer in their code, I have an draft of how we could do this if this feature idea is accepted. How it would work is pulling the current list of x (project, job_templates etc) and compare that list vs the list in code and make a delete call before updating/creating any new content when a specific variable is set to true that they want to remove old items.

**Comment by Tompage1994** [comment]
I would definitely be interested in seeing your example played out. Perhaps even if it isn't something which would go directly into the roles, it could be a playbook in this collection instead perhaps. If you could put together a small example and raise a PR that would be awesome

**Comment by djdanielsson** [comment]
here it is for you to look at, I am running into issues with my controller atm so I haven't been able to test it, I am sure there are changes that need to be made before it's working. I will try and continue working on it when I can and help fully test it out.

**Comment by Tompage1994** [comment]
Closed by #242
