### ISSUE TITLE
Tower version & Tower collection versus releases

### ISSUE THREAD

**Issue by Warkdev** [redhat-cop/automate_tower_genie_collections#250]
Hello,

Is there a way to know with which Tower API version the releases are applying ?

It's not easy to know when we've to use one or another collection :)

Thanks

**Comment by sean-m-sullivan** [comment]
on ansible galaxy we publish the tower configuration v1.5.2-3.8.2 as it was last tested and updated for use on 3.8.2. 
on controller_configuration, We've been keeping it line with the major version of the Ansible Automation Platform 2.0.0-1 and 2.1.0
However I've been using the 2.1.0 with a 3.8.4 server, and awx.awx 19.4.0. It's built to be versatile.

**Comment by Cedric-Ser** [comment]
Thank you Sean for your answer,

I remember having used the version v1.5.2 with 3.8.1 and having troubles with some missing API variables. I then downgraded to 1.4.1 and most of the issues have been solved except that some key features (such as approval node in workflow) are not supported by the underlying tower collection for 3.8.1.

Shall I upgrade Tower to a later version ? Or use a Tower collection for at least version 3.8.2 and upgrade this collection usage to v1.5.2-3.8.2 ?

Regards,

Cédric

**Comment by sean-m-sullivan** [comment]
What version of tower are you using? From what I can recall, even the controller_configuration should still work with 3.8.x instances. along with the latest awx.awx or ansible.tower collection. I don't think we ever tested on 3.7.x though. In general what happens is that the roles need to match the modules in awx.awx. the modules are what actually interact with tower. If you can give me an example of what was missing, then I can try and track down where the specific problem or change was to recommend a version.

**Comment by sean-m-sullivan** [comment]
@Cedric-Ser Will close this soon as an issue, unless you have further questions?

**Comment by Cedric-Ser** [comment]
Hello Sean,

I agree, I haven't had time to check it lately but I'll re-open the issue as soon as I can :)

Thanks for checking !

Cédric S.
