### ISSUE TITLE
Diff Assumes object assigned to orgs

### ISSUE THREAD

**Issue by bluealein56** [redhat-cop/automate_tower_genie_collections#272]
Diff Assumes object assigned to orgs. Credential is owned by the user admin

TASK [Find the difference of Project between what is on the Controller versus curated list.] ***************************************************************************************************************
task path: /home/toweradmin/controller_config/playbooks/controller_diff.yml:31
fatal: [tower.com]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'redhat_cop.controller_configuration.controller_object_diff'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Key: 'organization' missing from item in compare_list item: {'name': 'artifactory', 'user': 'admin', 'credential_type': 'Container Registry', 'inputs': {'host': 'docker.artifactory.company.com', 'username': 'jxhhhh', 'verify_ssl': False}}"
}

**Comment by djdanielsson** [comment]
this will be tracked in redhat-cop/aap_configuration_extended#31
