### ISSUE TITLE
Diff fails when API returns one object

### ISSUE THREAD

**Issue by bluealein56** [redhat-cop/automate_tower_genie_collections#273]
Diff appears to fail if there is only one object currently on Controller

TASK [Find the difference of Project between what is on the Controller versus curated list.] ***************************************************************************************************************
task path: /home/toweradmin/controller_config/playbooks/controller_diff.yml:31
fatal: [tower.com]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'redhat_cop.controller_configuration.controller_object_diff'. Error was a <class 'ansible.errors.AnsibleOptionsError'>, original message: Invalid type for configuration option plugin_type: lookup plugin: ansible_collections.redhat_cop.controller_configuration.plugins.lookup.controller_object_diff setting: api_list : Invalid type provided for \"list\": {'id': 6, 'type': 'o_auth2_application', 'url': '/api/v2/applications/6/', 'related': {'tokens': '/api/v2/applications/6/tokens/', 'activity_stream': '/api/v2/applications/6/activity_stream/'}, 'summary_fields': {'organization': {'id': 9, 'name': 'dev', 'description': 'dev'}, 'user_capabilities': {'edit': True, 'delete': True}, 'tokens': {'count': 0, 'results': []}}, 'created': '2022-01-24T21:50:20.445640Z', 'modified': '2022-01-24T21:50:20.445703Z', 'name': 'maas_api', 'description': 'Hardware Server team for making network change requests', 'client_id': '*********', 'client_secret': '************', 'client_type': 'confidential', 'redirect_uris': '', 'authorization_grant_type': 'password', 'skip_authorization': False, 'organization': 9}"
}

**Comment by djdanielsson** [comment]
this will be tracked in redhat-cop/aap_configuration_extended#31
