### ISSUE TITLE
Support "Registry Credentials" type

### ISSUE THREAD

**Issue by jtudelag** [redhat-cop/automate_tower_genie_collections#274]
AAP 2.1 supports "Registry Credentials" type. Mainly to pull Execution Environments from private registries. 

It would be awesome to be able to have it included in this collection as one of the valid credentials.

Thanks!!

**Comment by djdanielsson** [comment]
are you getting an error trying to use that credential type? If so, please post it.

**Comment by sean-m-sullivan** [comment]
the module and role should allow for any credential type to be used that exists on the API, Error would help, but I would check that your name matches one listed at
https://controller.node/api/v2/credential_types/ for your AAP

**Comment by djdanielsson** [comment]
Also make sure you have the most current version of ansible.controller or awx.awx collection because that might be your issue

**Comment by jtudelag** [comment]
Hey @sean-m-sullivan @djdanielsson you are right, I opened the ticket because I coul not see that cred type in the README, but it is working, I could create a Container Registry cred, so I am closing the issue.

thanks or your help!
