### ISSUE TITLE
Rename Repository to controller_configuration

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#278]
Its likely time to rename this to controller configuration. 

We just need to update the links in galaxy so our next published build goes to the right place, 

We will do this soon unless there are objections

**Comment by djdanielsson** [comment]
big fan of this idea

**Comment by sean-m-sullivan** [comment]
I just checked, and there are no changes to be made in the code, it should pick it up automatically.

**Comment by sean-m-sullivan** [comment]
@ericzolf @Tompage1994 any objections?

**Comment by Tompage1994** [comment]
No objections from me. I think this change is probably overdue and I think you're right that there shouldn't be any changes required in the code

**Comment by sean-m-sullivan** [comment]
Done
