### ISSUE TITLE
Remove references to tower_cli from examples/configs/templates.yml

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/automate_tower_genie_collections#279]
References to tower_cli should be removed and replaced either with collection usage or perhaps curl/API example (we could possibly use awxkit but it's not supported):

```
$ grep -r tower.cli 
grep: .git/objects/pack/pack-d920d9645030e1328d1dadaceebeabe610a63afb.pack: binary file matches
examples/configs/templates.yml:# tower-cli job_template survey --name="my job template" -f yaml
examples/configs/templates.yml:# https://github.com/ansible/tower-cli/blob/master/docs/source/cli_ref/usage/SURVEYS.rst
examples/configs/templates.yml:# You can retrieve a job along with its survey spec using tower cli as follows:
examples/configs/templates.yml:# tower-cli receive --job_template <Name> --user admin --format yaml
```

**Comment by ikke-t** [comment]
and perhaps point them to this blog: https://www.ansible.com/blog/automation-controller-workflow-deployment-as-code

I used awx.awx.export to get the data out. Unfortunately this tower_configuration doesn't accept back the yaml that the export generates.

**Comment by ikke-t** [comment]
just saying, that as a new user, I have no idea what tags the template creation accepts. How to define variables, how to set each option?
