### ISSUE TITLE
Using this as a project in Controller???

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#298]
So I had the bright idea because awx/controller doesn't alllow the users to use a collection as a source for playbooks, but they could definitely point here, should we modify the 'repo' to have a collections/requirements.yml to make it project compatible?

**Comment by Tompage1994** [comment]
Not sure I like that. Mostly because it just *feels* wrong. The whole point of the playbooks is to import them yourself and you're always going to want to include your own vars so I can't necessarily see the value.

**Comment by djdanielsson** [comment]
well to be fair the vars could be imported into inventory and that doesn't matter. the playbook, on the other hand, is the issue. We could just have a generic one that calls every role but that doesn't seem optimal. I think I agree with Tom, that while it's an interesting idea, in practice it just wouldn't work out that well.

**Comment by sean-m-sullivan** [comment]
Hence why I created an issue around it, Its not going to look right, its going to feel wrong, but was trying to figure out how to do it right. I think the other way would just be a plain repo that has the main COP collections, playbooks, and a requirements file, for people to point to and run off of :)

**Comment by djdanielsson** [comment]
It could be interesting to try and build out a demo repo for all our CoP AAP collections

**Comment by sean-m-sullivan** [comment]
Closing this, as this should remain collection, whether or not to offer another repo to clone from is another q
