### ISSUE TITLE
Issue with async on projects

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#299]
My customer is seeing issues with using v2.1.4 where the project creation is failing to pick up the async job id.

I haven't much more info but wanted to track this so we can test it out. I'm very busy this week so don't have the time to test this myself.

Error they get:

```
TASK [redhat_cop.controller_configuration.projects : Configure Controller Projects | Wait for finish the projects creation] *********************************

failed: [localhost] (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '551356648062.50', 'results_file': '/home/runner/.ansible_async/551356648062.50', 'changed': False, '__controller_project_item': {'name': 'XXX | Playbooks', 'organization': 'XXX', 'scm_branch': 'master', 'scm_clean': 'yes', 'scm_credential': 'XXX | SCM Access', 'scm_delete_on_update': 'yes', 'scm_type': 'git', 'scm_update_on_launch': 'yes', 'scm_update_cache_timeout': 900, 'scm_url': 'ssh://[git@git.example.com/xxx/playbooks.git'](http://git@git.example.com/xxx/playbooks.git')}, 'ansible_loop_var': '__controller_project_item'}) => {"__projects_job_async_results_item": {"__controller_project_item": {"name": "XXX | Playbooks", "organization": "XXX", "scm_branch": "master", "scm_clean": "yes", "scm_credential": "XXX | SCM Access", "scm_delete_on_update": "yes", "scm_type": "git", "scm_update_cache_timeout": 900, "scm_update_on_launch": "yes", "scm_url": "ssh://[git@git.example.com/xxx/playbooks.git](http://git@git.example.com/xxx/playbooks.git)"}, "ansible_job_id": "551356648062.50", "ansible_loop_var": "__controller_project_item", "changed": false, "failed": 0, "finished": 0, "results_file": "/home/runner/.ansible_async/551356648062.50", "started": 1}, "ansible_job_id": "551356648062.50", "ansible_loop_var": "__projects_job_async_results_item", "attempts": 1, "changed": false, "finished": 1, "msg": "could not find job", "results_file": "/root/.ansible_async/551356648062.50", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

If someone has a chance to take a look that would be super helpful
Thanks

**Comment by sean-m-sullivan** [comment]
Version of ansible and tower?

**Comment by djdanielsson** [comment]
2.1.4 or 2.1.3? because when i pull from galaxy it has been coming back as 2.1.3 still. I have not seen any issues with projects on 2.1.3

**Comment by Tompage1994** [comment]
You're right, it was v2.1.3.

Version of Ansible Controller will likely be the latest (its AAP2.1 I'm pretty certain). Have confirmed with the customer and will let you know if its not.

**Comment by djdanielsson** [comment]
are they running this on controller in the UI to configure controller? Because I just found that doesn't seem to work with async.

**Comment by Tompage1994** [comment]
Yes they are. And if that doesn't work that's a major problem because that's a pattern that is being used a lot.

**Comment by sean-m-sullivan** [comment]
@djdanielsson @Tompage1994 define UI, like through a job template, I'm running 3.8.x tower and its not having any issue. If its having a problem running async in containers, hrm...... i smell ticket

**Comment by sean-m-sullivan** [comment]
Also our latest tag is 2.1.4, why isn't it on galaxy, why didnt the release run?

**Comment by djdanielsson** [comment]
Yes, I am talking about when trying to run through a job template on controller itself it will fail to find the job id it seems. and I am not sure why 2.1.4 isn't in galaxy but I just know that it is not.

**Comment by sean-m-sullivan** [comment]
Got the same error
```
TASK [redhat_cop.controller_configuration.settings : Configure Settings | Wait for finish the Settings creation] ***
{
  "started": 1,
  "finished": 1,
  "stdout": "",
  "stderr": "",
  "stdout_lines": [],
  "stderr_lines": [],
  "ansible_job_id": "710259499483.77",
  "results_file": "/root/.ansible_async/710259499483.77",
  "msg": "could not find job",
  "invocation": {
    "module_args": {
      "jid": "710259499483.77",
      "mode": "status",
      "_async_dir": "/root/.ansible_async"
    }
  },
  "_ansible_no_log": false,
  "attempts": 1,
  "changed": false,
  "__controller_setting_job_async_results_item": {
    "failed": 0,
    "started": 1,
    "finished": 0,
    "ansible_job_id": "710259499483.77",
    "results_file": "/home/runner/.ansible_async/710259499483.77",
    "changed": false,
    "__controller_setting_item": {
      "settings": {
        "AUTH_LDAP_BIND_PASSWORD": "password",
        "AWX_TASK_ENV": {
          "GIT_SSL_NO_VERIFY": "True"
        },
        "AUTH_LDAP_SERVER_URI": "ldap://ldap.example.com",
        "AUTH_LDAP_USER_DN_TEMPLATE": "uid=%(user)s,ou=Users,dc=example,dc=com",
        "AUTH_LDAP_GROUP_SEARCH": [
          "dc=example,dc=com",
          "SCOPE_SUBTREE",
          "(objectClass=person)"
        ],
        "AUTH_LDAP_GROUP_TYPE": "GroupOfUniqueNamesType",
        "AUTH_LDAP_USER_SEARCH": [
          "OU=Users,DC=example,DC=com",
          "SCOPE_SUBTREE",
          "(cn=%(user)s)"
        ],
        "AUTH_LDAP_START_TLS": true,
        "AUTH_LDAP_GROUP_TYPE_PARAMS": {},
        "AUTH_LDAP_REQUIRE_GROUP": "cn=satellite-qe,ou=adhoc,ou=managedGroups,dc=example,dc=com",
        "AUTH_LDAP_USER_ATTR_MAP": {
          "first_name": "displayName",
          "last_name": "sn",
          "email": "examplePrimaryMail"
        },
        "AUTH_LDAP_USER_FLAGS_BY_GROUP": {
          "is_superuser": [
            "cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=example,dc=com"
          ]
        },
        "AUTH_LDAP_ORGANIZATION_MAP": {
          "Satellite": {
            "users": true
          }
        },
        "AUTH_LDAP_TEAM_MAP": {
          "satellite-qe": {
            "organization": "Satellite",
            "users": true
          },
          "satlab-admin": {
            "organization": "Satellite",
            "users": "cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=example,dc=com"
          }
        }
      }
    },
    "ansible_loop_var": "__controller_setting_item"
  },
  "ansible_loop_var": "__controller_setting_job_async_results_item",
  "_ansible_item_label": {
    "failed": 0,
    "started": 1,
    "finished": 0,
    "ansible_job_id": "710259499483.77",
    "results_file": "/home/runner/.ansible_async/710259499483.77",
    "changed": false,
    "__controller_setting_item": {
      "settings": {
        "AUTH_LDAP_BIND_PASSWORD": "password",
        "AWX_TASK_ENV": {
          "GIT_SSL_NO_VERIFY": "True"
        },
        "AUTH_LDAP_SERVER_URI": "ldap://ldap.example.com",
        "AUTH_LDAP_USER_DN_TEMPLATE": "uid=%(user)s,ou=Users,dc=example,dc=com",
        "AUTH_LDAP_GROUP_SEARCH": [
          "dc=example,dc=com",
          "SCOPE_SUBTREE",
          "(objectClass=person)"
        ],
        "AUTH_LDAP_GROUP_TYPE": "GroupOfUniqueNamesType",
        "AUTH_LDAP_USER_SEARCH": [
          "OU=Users,DC=example,DC=com",
          "SCOPE_SUBTREE",
          "(cn=%(user)s)"
        ],
        "AUTH_LDAP_START_TLS": true,
        "AUTH_LDAP_GROUP_TYPE_PARAMS": {},
        "AUTH_LDAP_REQUIRE_GROUP": "cn=satellite-qe,ou=adhoc,ou=managedGroups,dc=example,dc=com",
        "AUTH_LDAP_USER_ATTR_MAP": {
          "first_name": "displayName",
          "last_name": "sn",
          "email": "examplePrimaryMail"
        },
        "AUTH_LDAP_USER_FLAGS_BY_GROUP": {
          "is_superuser": [
            "cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=example,dc=com"
          ]
        },
        "AUTH_LDAP_ORGANIZATION_MAP": {
          "Satellite": {
            "users": true
          }
        },
        "AUTH_LDAP_TEAM_MAP": {
          "satellite-qe": {
            "organization": "Satellite",
            "users": true
          },
          "satlab-admin": {
            "organization": "Satellite",
            "users": "cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=example,dc=com"
          }
        }
      }
    },
    "ansible_loop_var": "__controller_setting_item"
  }
}
```

**Comment by sean-m-sullivan** [comment]
Put my error above, but Got the same error using this project
https://github.com/sean-m-sullivan/controller_project
and its requirements.yml is 
```
---
collections:
  - name: awx.awx
  - name: https://github.com/sean-m-sullivan/tower_configuration.git
    type: git
    version: add_galaxy
...
```
a DEVEL clone of the repo. So its not fixed in 2.14

**Comment by sean-m-sullivan** [comment]
And it looks like we are not the only ones
https://github.com/ansible/awx/issues/11521
https://github.com/ansible/ansible-runner/issues/1024

**Comment by sean-m-sullivan** [comment]
as much as I hate it, should we split the roles into two parts with a main file, that will point to async, no async, with async being off by default by now. I LOVE how fast it runs with async, but if its underlying AAP/Awx issues, this could be a valid workaround.

**Comment by Tompage1994** [comment]
> And it looks like we are not the only ones
> https://github.com/ansible/awx/issues/11521
> https://github.com/ansible/ansible-runner/issues/1024

I'll chase up with @lshake who raised that AWX issue and see if he's got an internal Jira ticket or something.

**Comment by Tompage1994** [comment]
Response:

The workaround is to set ansible_async_dir on each task.

```
  tasks:
    - name: kick off async task
      ansible.builtin.command: "sleep {{ task_time }}"
      register: task_result
      async: 120
      poll: 0
      vars:
        ansible_async_dir: '/tmp/.ansible_async'

    - name: check task status
      ansible.builtin.async_status:
        jid: "{{ task_result.ansible_job_id }}"
      register: async_poll_results
      retries: 60
      delay: 2
      until: async_poll_results.finished
      vars:
        ansible_async_dir: '/tmp/.ansible_async'
```

**Comment by Tompage1994** [comment]
No resolution in sight on the actual fix for it but the workaround may work?

**Comment by djdanielsson** [comment]
the workaround was pushed in 2.1.4, we should keep an eye on the actual fix and once it has been implemented we can remove our workaround.

**Comment by Klaas-** [comment]
can we remove the workaround again because https://github.com/ansible/ansible-runner/pull/1027 is merged?

**Comment by sean-m-sullivan** [comment]
No, this collection is largely backward compatible, I don't see a reason to remove something like this that is working for a bit.

**Comment by Klaas-** [comment]
> No, this collection is largely backward compatible, I don't see a reason to remove something like this that is working for a bit.

I talked about this on matrix a little, right now this has a negative side effect if you're using this role outside of a temporary environment. It'll create a tmp directory that belongs to the remote user on the target host, if you are using this collection with multiple users you'll get into ACL problems. It also won't clean up after itself like ansible usually does ( https://github.com/ansible/ansible/blame/2f647e9617067802647d2a461906c1241c5cac00/docs/docsite/rst/playbook_guide/playbooks_async.rst#L104-L107 ).
But maybe this can also just be a warning in the readme to clean the dir in the playbook you are using to call controller_configuration

**Comment by Tompage1994** [comment]
I guess we could make it a settable variable (defaulted to the current value) so it can be changed if necessary?

**Comment by sean-m-sullivan** [comment]
@Klaas- I was not aware of this, and had not read the matrix conversation, I wonder if we change it to be random, have be able to be set, set a role with a handlers and clean it up at end of playbooks, remove it entirely, there is a lot of ways to go about it, I wonder if we should set a different conversation to capture all of this.

**Comment by djdanielsson** [comment]
I have been thinking about this, my question is do we want to make a temp file per role? And thus have to create and delete dozens of them? Or should we create 1 folder and create one task to delete it. The one thing idk would be if you can use the same handler across them all and it only trigger once, might be worth testing.

**Comment by Klaas-** [comment]
> I have been thinking about this, my question is do we want to make a temp file per role? And thus have to create and delete dozens of them? Or should we create 1 folder and create one task to delete it. The one thing idk would be if you can use the same handler across them all and it only trigger once, might be worth testing.

I have been thinking about this today as well, the problem with the collection is that there is no generals for all roles (at least not afaik). 

I have two solutions in mind if you want to keep the workaround for backwards compatibility: use a new variable, that is by default undefined, all usage of ansible_async_dir could then be changed to `{{ controller_configuration_async_dir | default('/tmp/.ansible_async') }}` or something along these lines, and then we could do a simple file with absent in dispatch role. 

Other option would be utilizing ansible.builtin.tempfile. I'd guess this needs to be handled in a meta role like dispatch for most usage scenarios. 

The only problem I see is that we also need to make people not using dispatch aware of this, maybe via the general readme file.

**Comment by djdanielsson** [comment]
I do not think tempfile is a good solution because that would be a breaking change for many users.
