### ISSUE TITLE
workflows example out of date

### ISSUE THREAD

**Issue by ikke-t** [redhat-cop/automate_tower_genie_collections#304]
I failed over and over again trying to follow this: https://github.com/redhat-cop/controller_configuration/blob/devel/examples/configs/workflows.yml

It apparently is out of date, this blog likely is closer to truth: https://www.ansible.com/blog/automation-controller-workflow-deployment-as-code

trying next the blog.

**Comment by ikke-t** [comment]
here's a sample that works: https://github.com/RedHatNordicsSA/cool-lab/blob/feature/add-aap-configs/aap_configs/aap_workflow_templates.yml.

There is also query and extra variables passing, which i wish would be added to example

**Comment by djdanielsson** [comment]
This is a duplicate of #297  so I am closing this one
