### ISSUE TITLE
Dispatcher Role

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#309]
This was brought up at the COP meeting, 
We should have a dispatcher role that invokes the rest of the roles. 
so like
redhat_cop.controller_configuration.controller_config_dispatch
will call this role set
https://github.com/redhat-cop/controller_configuration/blob/f99a1c9e020e3a6f1dbb6ace280840397e7f757b/playbooks/configure_controller.yml#L50

**Comment by sean-m-sullivan** [comment]
Basic idea is this would be a meta role in place of a playbook to call the other roles.

**Comment by djdanielsson** [comment]
I would like to test making a playbook that someone could import instead of another role. a role calling roles with no other additional function I am not a fan of.

**Comment by Tompage1994** [comment]
@djdanielsson @sean-m-sullivan I've implemented this role (#314) (there were only a few bits of pain trying to work out how to evaluate the vars etc.). I think the solution it provides is pretty nice and now I've seen a practical application of it I'm onboard as it gives the option to run a subset of the tasks and also allows you to have your own way to define vars etc. whereas the playbook you can import is very rigid.

I think I like the flexibility this provides and at worse it's something nobody will use. Happy for the PR to be closed though if we decide against this implementation.

**Comment by sean-m-sullivan** [comment]
And agreed on the last part, I think at worst people don't use it, I think the only downside is unable to use tags to run some parts, but at same time its flexible for people to use.
