### ISSUE TITLE
RFE: make include_vars a bit smarter

### ISSUE THREAD

**Issue by fvzwieten** [redhat-cop/automate_tower_genie_collections#331]
The controllor_configure.yml playbook has a pre task to import the vars files from the configs dir. In it's current form it's rather picky on what it finds there. I make a GitHub repo for my configs adding a readme.md and the directory then has a hidden .git subdir. The playbook borked at both.

Suggest to add "file_matching" and/or "ignore_unknown_extensions" to this pre-task.

Related:
the repo readme states this:
"The awx command line can export json that is compatible with this collection."
However, the playbook only seems to accept yml format, although include_vars is able to parse json.

**Comment by djdanielsson** [comment]
the controller_configure.yml is just an example, this is a fair point and thanks for pointing it out. I personally use group_vars and don't import any vars except vaulted file. There are some plans to revamp our examples.

**Comment by djdanielsson** [comment]
we have removed examples from this repo, there are a few repos out there that we promote if someone is looking for an example. we have the controller_configure.yml playbook as something that some people with simple use cases can use but in my opinion everyone should have their own playbook along with their own configs to allow for exact customization for their use case.
