### ISSUE TITLE
Remove json_query and jmespath dependency from filetree_create

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#341]
As per #246 the community.general collection isn't a trusted collection (i.e. in Cloud Automation hub) so we should try to avoid it if possible. Having a quick look we should be able to replace with a map.

Also its not ideal asking the user to need to go and install jmespath

**Comment by djdanielsson** [comment]
it also isn't maintained which is a big reason why it isn't in core, I agree we should try and remove it if possible

**Comment by sean-m-sullivan** [comment]
Agreed, it should be on our list to do, most likely using a filter or a module to do the lifting, For now its a stop gap
