### ISSUE TITLE
Add support to configure permissions/access for job templates, projects, inventories

### ISSUE THREAD

**Issue by eschek87** [redhat-cop/automate_tower_genie_collections#342]
Currently it is not possible to configure the access permissions to job templates, projects, inventories. This needs to be done manually on the ansible controller webui. It would be cool to also have this as "configuration as code" :-)

Regards,
Stephan

**Comment by Tompage1994** [comment]
Hi Stephan,

you should be able to make use of the [roles role](https://github.com/redhat-cop/controller_configuration/tree/devel/roles/roles) (sorry for the confusing name) to be able to do this. Take a look at the readme there and if this isn't covering what you're asking let me know

**Comment by eschek87** [comment]
Hi Tompage1994,
awesome! That was what I was looking for. Didn't see it. Thanks.
