### ISSUE TITLE
Suggestion to apply naming standards to objects

### ISSUE THREAD

**Issue by ansiblejunky** [redhat-cop/automate_tower_genie_collections#359]
Feature request...

When it comes to naming conventions, this is also critical for new objects (JTs, Creds, Cred Types, Inventory, Projects, etc).  It would be great to have a role built that enforces naming standards (maybe this is a stretch and should be left to linter tool) but at least to provide a variable whereby when set, the roles would prefix all objects with that.

For example, create the following Job Templates, Inventories and Projects with the variable:
```
controller_name_prefix: acme
```
Then all inventory objects will look like...
```
acme_aws_inventory
acme_azure_inventory
acme_local_inventory
```

It really works the best when we offer perhaps a role that applies some regex conversion rule to convert whatever is written as the NAME of the object to perhaps a set of rules: lowercase, only underscore (not dashes), with company prefix. 

This can also help with the other issue of using config-as-code when object names change, it will be replicated to Site 1 and Site 2 (in our ref arch) and then someone either has to go and delete it, or perhaps use some diff mechanism (I heard we are working on that).

**Comment by djdanielsson** [comment]
This is too subjective and too many orgs have naming standards that while we could agree they are not best practice, those users would still have to use that standard. Also this would go against CasC because your objects then would not match your code because on the fly they are being renamed to something else.

**Comment by djdanielsson** [comment]
I agree this would be best at the linter level to enforce if so desired.

**Comment by sean-m-sullivan** [comment]
This sounds really neat, but I think its better to enforce via LInt, and through PRS at the org level, Everything should be Peer reviewed, when added, its one of those CasC benefits.

**Comment by ansiblejunky** [comment]
Yeah, I understand the feedback/comments. I'm looking at ansible-lint but that doesn't seem the right place since it focuses more on ansible core elements, versus controlling/checking the name of the object itself that is created (creds/inventory/etc).  

Happy to write something for this, but trying to think of where the appropriate place might be. 

One idea I had was a simple filter plugin but I'd have to add `| myfilter }}` to each object definition.. but doesn't seem the best idea either. 

The initial ask was not for us to be opinionated and demand a specific naming standard, but to offer a way for customers to define the naming standard using their own regex pattern. Then we only provide a mechanism to apply that to the name of the objects before we update/create it.

**Comment by djdanielsson** [comment]
honestly that would be a nightmare to support, especially if we allowed them their own regex. I would look at yaml linter for this type of thing, because really we are taking yaml lists as inputs for the roles in this collection.
