### ISSUE TITLE
project scm_branch bug

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/automate_tower_genie_collections#366]
if you pass 'scm_branch: ""  ' and in the UI or old code had set scm_branch to something else this does not over ride the UI and set it to blank/default which should be the result.

**Comment by Tompage1994** [comment]
Would this not then be a bug in the underlying module? or is the `""` not being passed on to it?

**Comment by Tompage1994** [comment]
Never mind, I assume this is our old friend `default(omit, true)` which means a value of `""` is omitted.
