### ISSUE TITLE
Uses of awx.awx.controller_api lookup will return paginated results

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#372]
This is an issue in all of the `object_diff` and `filetree_create` roles.

Also would be good to update our documentation around the diff plugin where we may have mentioned the controller_api lookup.

**Comment by djdanielsson** [comment]
what about #351 ? I thought that allowed it to uses either one.

**Comment by ivarmu** [comment]
Is that a duplicate of #440 ?

**Comment by Tompage1994** [comment]
> 

Yes, closing
