### ISSUE TITLE
filetree_write role uses ansible.controller.controller_api in 2.1.7

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#383]
I'm getting this error with the version 2.1.7 of the collection. while trying to use filetree_write
```
TASK [redhat_cop.controller_configuration.filetree_create : Check if the connection is to an Ansible Tower or to Automation Platform] ******************************************************************
fatal: [localhost]: FAILED! => {"msg": "lookup plugin (ansible.controller.controller_api) not found"}
```

AFAIK and ss specified in the doc, the dependance should be on awx.aw.controller_api as ansible.tower is not available.

**Comment by silvinux** [comment]
Hello,

If the ansible collection is not installed at the default path, it should be specified exporting the variable `COLLECTIONS_PATHS` or in the ansible.cfg.
```
$ cat ansible.cfg 
[defaults]
collections_paths = ./collections 
```
Basically, the role verify the below command:

```
$ ansible-galaxy collection list --collections-path collections
[WARNING]: Collection at '/home/ansible/test-tags/tags-example-1/collections/ansible_collections/redhat_cop/controller_configuration' does not have a MANIFEST.json file, nor has it
galaxy.yml: cannot detect version.

# /home/ansible/test-tags/tags-example-1/collections/ansible_collections
Collection                          Version
----------------------------------- -------
ansible.controller                  4.2.0  
ansible.utils                       2.6.1  
community.general                   5.7.0  
redhat_cop.controller_configuration * 
```

Hope it helps,
Cheers

**Comment by nodje** [comment]
Hi, 

thanks for your answer, but I don't understand:
the requirements in the doc are for the awx.awx collection and redhat_cop.controller_configuration.

awx.awx contains a plugin `controller_api`, which unless coincidentally bearing the exact same name, seems to be similar to `ansible.tower.controller_api` (since the two namespaces awx/tower often provide the same content).

And besides, https://galaxy.ansible.com/ansible/controller just isn't available.
Why not use `awx.awx.controller_api` in the filetree_write role?

**Comment by djdanielsson** [comment]
I thought this was supposed to be handled by #351 I will have to look into it a bit more to answer but no awx.awx is not the answer

**Comment by adonisgarciac** [comment]
Hi @nodje, awx.awx is the community collection and ansible.controller (4.0.0 ansible.tower renamed to ansible.controller) is collection certified by Red Hat (think as a downstream version of awx.awx). For this reason, you can see the same modules, plugins, etc.. in both collections.

As @djdanielsson say, There were changes to do filetree_create and object_diff smarter to auto-discover which collection you have installed. These changes are not present in release 2.1.7 but you can use them generating a collection from devel branch in this repository. I hope we will have a new release ASAP with a lot of new features and fixes :)

**Comment by nodje** [comment]
Hi @adonisgarciac ,

>awx.awx is the community collection and ansible.controller (4.0.0 ansible.tower renamed to ansible.controller) is collection certified by Red Hat (think as a downstream version of awx.awx). For this reason, you can see the same modules, plugins, etc.. in both collections.

Precisely, and since the required dependency for the project is on awx.awx, my point was, why use the downstream for controller_api when the entire project is already dependent on upstream awx.awx ?

> 4.0.0 ansible.tower renamed to ansible.controller
This is what tricked me. Since I have an old version of ansible.tower installed but no controller_api in it, I couldn't figure what ansible.controller was.
And both ansible.tower and ansible.controller are to be found in https://console.redhat.com/ansible/automation-hub/repo/published/ansible and not in Galaxy....

**Comment by nodje** [comment]
Still, the doc should specify the collection `ansible.controller` as a requirement since it's necessary to run the roles

**Comment by adonisgarciac** [comment]
Where do you see dependency with awx.awx? Can you share with us the links? We always try to do this collection as general as we can and it shouldn't have any dependency with awx.awx, it should be general to allow user choose between awx.awx or ansible.controller.

**Comment by nodje** [comment]
I see it here https://github.com/redhat-cop/controller_configuration#requirements

But I now realize it's a OR: `The AWX.AWX OR ANSIBLE.CONTROLLER collections MUST be installed`, so either works.

Hence the remark of @djdanielsson which underlines that both source should work for controller_api collection
