### ISSUE TITLE
Project_update Role Issue

### ISSUE THREAD

**Issue by sudhann92** [redhat-cop/automate_tower_genie_collections#385]
Hi Team,

I just found one glitch in project_update role. In project_update role below condition is not working properly. Seems item.**update** is a built in function or method that why its not taking this variable as Boolean type. Hope if we change the variable name means it will work as expected.
  when:
    - controller_projects is defined
    **- __project_update_update_item.update**
    - __project_update_update_item.state | default('present') != "absent"
    -
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/project_update/tasks/main.yml
    
**__project_update_update_item.update** this is current 
**__project_update_update_item._update** if we change like this means the condition will work 

Also we need to change the "update" variable in project role. Kindly correct me if am wrong means

**Comment by djdanielsson** [comment]
do you have actual errors or 2 code sets to show the bug that I could try and replicate? I have reviewed the code and I believe it is correct as is.

**Comment by sudhann92** [comment]
Hi @djdanielsson 
Actually i don't see any error but the condition which mention in project_update role not working properly . As per code if the **update** is true means then project sync should happen i guess. but whatever inside in project.yml file for all project seems source sync is happening 

 Below value i have given in project.yml file when I tried with current code for project_update role its triggering sync for all project but it should need to check the "**update**" condition rite . As per condition project_update should need to run for this project only "TEST_workflow_Project" but its sync all the one
************************************************************
----
  controller_projects
  - name: "Customer Vault Associate 
    scm_type: git
    scm_url: https:
    scm_branch: "test"
    scm_clean: true
    description: project
    organization: "test"
    credential: xxxxxct
    wait: true
    scm_delete_on_update: true
    scm_update_on_launch: true

  - name: "Customer template Role Associate
    scm_type: git
    scm_url: https:
    scm_branch: "test"
    scm_clean: true
    description: project to give permission for your Object to some other team
    organization: "test"
    credential: XXcrtrl
    wait: true
    **update: false**
    scm_delete_on_update: true
    scm_update_on_launch: true


  - name: "TEST_workflow_Project"
    scm_type: git
    scm_url: https:
    scm_branch: develop
    scm_clean: true
    description: workflow testing
    organization: "test"
    credential: XXctr
    wait: true
    **update: true**
    scm_delete_on_update: true
    scm_update_on_launch: true
*************************************************************

I have tried from my end just changing variable value then the "**update**" condition is working fine in project_update role its skipped the two set of project and it ran only the "_update" true value in project_update code
**************************************************
----
  controller_projects
  - name: "Customer Vault Associate 
    scm_type: git
    scm_url: https:
    scm_branch: "test"
    scm_clean: true
    description: project
    organization: "test"
    credential: xxxxxct
    wait: true
    scm_delete_on_update: true
    scm_update_on_launch: true

  - name: "Customer template Role Associate
    scm_type: git
    scm_url: https:
    scm_branch: "test"
    scm_clean: true
    description: project to give permission for your Object to some other team
    organization: "test"
    credential: XXcrtrl
    wait: true
    **_update: false**
    scm_delete_on_update: true
    scm_update_on_launch: true


  - name: "TEST_workflow_Project"
    scm_type: git
    scm_url: https:
    scm_branch: develop
    scm_clean: true
    description: workflow testing
    organization: "test"
    credential: XXctr
    wait: true
    **_update: true**
    scm_delete_on_update: true
    scm_update_on_launch: true
***********************************************************
Just added the underscore before update and given default value as false. Seems if the variable is "_update" available in project yaml then it will check the actual boolen if not available means by default value it will take 
  when:
    - controller_projects is defined
    - **__project_update_update_item._update | default(false)**
    - __project_update_update_item.state | default('present') != "absent"

kindly check from your end and also correct means if am wrong here.

Just sharing whole code for project_update and bold the changes one 

---
# Update Controller Projects
- name: Run Controller project update
  project_update:
    name:                     "{{ __project_update_update_item.name }}"
    organization:             "{{ customer_as_code_organization | default(omit, true) }}"
    wait:                     "{{ __project_update_update_item.wait | default(omit) }}"
    interval:                 "{{ __project_update_update_item.interval | default(1) }}"
    timeout:                  "{{ __project_update_update_item.timeout | default(omit, true) }}"

    controller_username:      "{{ controller_username | default(omit, true) }}"
    controller_password:      "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:    "{{ controller_oauthtoken | default(omit, true) }}"
    controller_host:          "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:   "{{ controller_config_file | default(omit, true) }}"
    validate_certs:           "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_projects }}"
  loop_control:
    loop_var: "__project_update_update_item"
  no_log: "{{ controller_configuration_project_update_secure_logging }}"
  when:
    - controller_projects is defined
    - **__project_update_update_item._update | default(false)**
    - __project_update_update_item.state | default('present') != "absent"
  async: 1000
  poll: 0
  register: __project_update_job_async
  changed_when: not __project_update_job_async.changed
  vars:
    ansible_async_dir: '/tmp/.ansible_async'

- name: "Configure Controller Projects | Wait for finish the projects creation"
  async_status:
    jid: "{{ __project_update_job_async_results_item.ansible_job_id }}"
  register: __project_update_job_async_result
  until: __project_update_job_async_result.finished
  retries: "{{ controller_configuration_project_update_async_retries }}"
  delay: "{{ controller_configuration_project_update_async_delay }}"
  loop: "{{ __project_update_job_async.results }}"
  loop_control:
    loop_var: __project_update_job_async_results_item
  when: __project_update_job_async_results_item.ansible_job_id is defined
  no_log: "{{ controller_configuration_project_update_secure_logging }}"
  vars:
    ansible_async_dir: '/tmp/.ansible_async'
...

**Comment by ivarmu** [comment]
a single test shows that @sudhann92 is right with the finding:

Given the following playbook:
```
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    data:
      - name: "name1"
        surname: "surname1"
        update: false
        do_update: false
      - name: "name2"
        surname: "surname2"
        update: true
        do_update: true
  tasks:
    - name: "debug 1"
      debug:
        msg:
          - "item: {{ item }}"
          - "item.update: {{ item.update }}"
          - "item.update type: {{ item.update | type_debug }}"
          - "item.do_update: {{ item.do_update }}"
          - "item.do_update type: {{ item.do_update | type_debug }}"
      loop: "{{ data }}"
      when:
        - item.update

    - name: "debug 2"
      debug:
        msg:
          - "item: {{ item }}"
          - "item.update: {{ item.update }}"
          - "item.update type: {{ item.update | type_debug }}"
          - "item.do_update: {{ item.do_update }}"
          - "item.do_update type: {{ item.do_update | type_debug }}"
      loop: "{{ data }}"
      when:
        - item.do_update
...
```

produces the following output:

```
ansible-playbook test.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [debug 1] *******************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'name1', 'surname': 'surname1', 'update': False, 'do_update': False}) => {
    "msg": [
        "item: {'name': 'name1', 'surname': 'surname1', 'update': False, 'do_update': False}",
        "item.update: <built-in method update of dict object at 0x7f2523904380>",
        "item.update type: builtin_function_or_method",
        "item.do_update: False",
        "item.do_update type: bool"
    ]
}
ok: [localhost] => (item={'name': 'name2', 'surname': 'surname2', 'update': True, 'do_update': True}) => {
    "msg": [
        "item: {'name': 'name2', 'surname': 'surname2', 'update': True, 'do_update': True}",
        "item.update: <built-in method update of dict object at 0x7f25239573c0>",
        "item.update type: builtin_function_or_method",
        "item.do_update: True",
        "item.do_update type: bool"
    ]
}

TASK [debug 2] *******************************************************************************************************************************************************************************************************************************
skipping: [localhost] => (item={'name': 'name1', 'surname': 'surname1', 'update': False, 'do_update': False}) 
ok: [localhost] => (item={'name': 'name2', 'surname': 'surname2', 'update': True, 'do_update': True}) => {
    "msg": [
        "item: {'name': 'name2', 'surname': 'surname2', 'update': True, 'do_update': True}",
        "item.update: <built-in method update of dict object at 0x7f2523914340>",
        "item.update type: builtin_function_or_method",
        "item.do_update: True",
        "item.do_update type: bool"
    ]
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

So it seems that creating a field called `update` for a dict object collides with its `update` method (see https://python-reference.readthedocs.io/en/latest/docs/dict/update.html).

So... it has sense to re-name the `update` field to `do_update` or something similar.

**Comment by sudhann92** [comment]
@ivarmu  
Yes exactly this what from starting itself i tried to explain in my comment. Seems 'update' is method in python.
Thank you for analyzed my finding and fixing the code. kindly let me know once code is updated in the branch
