### ISSUE TITLE
'settings' extraction with filetree_create ?

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#392]
I'm using a recent download of the `devel` branch.

`ansible-playbook -e @localvars.yml filetree_write.yml  -e '{input_tag: [all]}'` doesn't extract any settings and using `input_tag: [settings]` isn't supported.
Though  `filetree_read` and `dispatch` do support `controller_settings`.

Is it a work in progress or are there any issue with extracting these values from the API ?

**Comment by adonisgarciac** [comment]
Settings object is pending to develop in filetree_create role. Then, WIP

Thanks a lot for the feedback. We already have a task in our to-do
