### ISSUE TITLE
When using filetree_create, seems to be missing required variable and doesn't execute the plugin-block

### ISSUE THREAD

**Issue by erikhjensen** [redhat-cop/automate_tower_genie_collections#401]
https://github.com/redhat-cop/controller_configuration/blob/a689549cd9336eb6d57922204d8147e31de26673/roles/filetree_create/tests/filetree_create.yml#L35

I've been trying to use this to export the information from Ansible Tower so that we can migrate to Ansible on Azure (or any AAP 2.x)  I've been running this playbook inside Ansible Tower itself and I can confirm that the collection is being downloaded by the project-refresh job in Tower.

Here is my experience w/ this role.

1)  When I include the sample playbook w/ the role included as shown in the sample, its assertions indicate that we are missing a required variable called "input_tag" where we specify which objects are being exported
- role: filetree_create
   vars:        
     input_tag:       
       - organizations
this is how I've satisfied that dependency, is that intended?

2) Next, it appears that the block of code which determines which dependency is installed (awx.awx vs ...controller) at the start of main.yaml does not run, 
`- name: "Check requirements (block)"`
and as such the variable controller_api_plugin is null.  I don't see any conditions that would prevent that block from running.  https://github.com/redhat-cop/controller_configuration/blob/9a5b7b984147cdcc5826f3c5be9c4573bb416c33/roles/filetree_create/tasks/main.yml#L21

2.1) this is the playbook output and we can see the block is skipped and the input variables validation are the first tasks run inside the role.

PLAY [all] *********************************************************************
TASK [Get the Authentication Token for the future requests] ********************
ok: [localhost]
TASK [Set the oauth token to be used since now] ********************************
ok: [localhost]
TASK [redhat_cop.controller_configuration.filetree_create : Check if the required input variables are present] ***
ok: [localhost]
TASK [redhat_cop.controller_configuration.filetree_create : Check if the required input values are correct] ***
ok: [localhost] => (item=organizations)
TASK [redhat_cop.controller_configuration.filetree_create : Include Tasks to get all objects of type [u'organizations']] ***
included: /tmp/bwrap_1356_rnogef3l/awx_1356_73duuht9/requirements_collections/ansible_collections/redhat_cop/controller_configuration/roles/filetree_create/tasks/all.yml for localhost
TASK [redhat_cop.controller_configuration.filetree_create : Get the Authentication Token for the future requests] ***
ok: [localhost]
TASK [redhat_cop.controller_configuration.filetree_create : Set the oauth token to be used since now] ***
ok: [localhost]
TASK [redhat_cop.controller_configuration.filetree_create : Check if the connection is to an Ansible Tower or to Automation Platform] ***
fatal: [localhost]: FAILED! => {"msg": "lookup plugin (ansible.controller.controller_api) not found"}
PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

I'm happy to continue to run a test if you have some thoughts of if this improper invocation or, mitigating circumstances due to Tower 3.8.

**Comment by erikhjensen** [comment]
I have one comment to add, i was using the devel branch for the above code links and for my troubleshooting reference but I see that the last release tag 2.1.7 is probably what's included in galaxy.. as such, I'm trying to find the corresponding code in galaxy to figure out where the plugin is being set in that version of the code.  The release 2.1.7 does not include the plugin-management block that I'd referred to in the OP.

When instead I try to fetch the latest from devel using the following requirements yaml (and variations therein (e.g. using git+ before https) it fails to sync

---
collections:
- name: awx.awx
- name: community.general
- name: redhat_cop.controller_configuration
  source: git+https://github.com/redhat-cop/controller_configuration.git
  type: git
  version: 57ec9b57ca182e2f2c11225c8c503b52fe088a77
  
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "collection", "install", "-r", "collections/requirements.yml", "--collections-path", "/var/lib/awx/projects/.__awx_cache/_56__ansible_tower_configuration_playbook/stage/requirements_collections"], "delta": "0:00:48.621379", "end": "2022-10-26 18:15:35.452392", "msg": "non-zero return code", "rc": 1, "start": "2022-10-26 18:14:46.831013", "stderr": "ERROR! Unknown error when attempting to call Galaxy at 'git+https://github.com/redhat-cop/controller_configuration.git/api': <urlopen error unknown url type: git+https>", "stderr_lines": ["ERROR! Unknown error when attempting to call Galaxy at 'git+https://github.com/redhat-cop/controller_configuration.git/api': <urlopen error unknown url type: git+https>"]


but despite that, the engine doesn't seem to like that schema whereas w/ roles/requirements.yaml the src:git+https... and scm:git values (in lieu of source and type) do work in our Tower 3.8 env.

Is it possible to pull the collection from the devel-latest using requirements.yml?

**Comment by adonisgarciac** [comment]
Hi @erikhjensen 

As you are telling, devel has changes since 2.1.7 version was released. The issue that you have, probably, it is because there is not a galaxy.yml in the repository. There is a template galaxy.yml.j2 (https://github.com/redhat-cop/controller_configuration/blob/devel/galaxy.yml.j2) which is to generate the galaxy.yml of releases with github actions (CI/CD). 

I suggest you to use devel in your tests because it has several changes and fixes which resolve bugs. I'm going to suggest for a new release but meanwhile, you can download this repository and build the collection, then, use this build for your tests.

About your first comment, I'm going to review if we can change input_tag var for normal tags. But yes, if you send the input_tag var to the role, it should work fine. You can do it as you tell or with an extra var for example.

**Comment by djdanielsson** [comment]
@adonisgarciac let me know what you find, we can do a new release if needed.

**Comment by ivarmu** [comment]
@erikhjensen You can easily build your testing release from the git repo (devel branch) making use of this repo: https://github.com/redhat-cop/ah_configuration

It's intended to manage the Automation Hub configuration as code, so it takes a git repo and populates a new release to an existing Automation Hub instance. You will need to generate your `galaxy.yml` file, as @adonisgarciac already mentioned. If you need help in this process I could provide some working example.

The `input_tags` variable was defined like this to show a more comprehensive error/warning message if one tries to export a non-supported or non-implemented object. We are thinking how we could do the same using regular ansible tags (as the ansible tags are not populated neither as environment nor extra variables). Any idea with this will be welcome!

**Comment by ivarmu** [comment]
> @adonisgarciac let me know what you find, we can do a new release if needed.

There has been so many changes since the last official release, so it would be a good idea to generate a new one.

**Comment by adonisgarciac** [comment]
@djdanielsson yes, I think that new release is needed because there are a lot of changes and fixes since 2.1.7

**Comment by erikhjensen** [comment]
Thanks for the comments folks.  I'll probably bias towards consuming the official released version once the new improvements are released.   I'm looking forward to more GitOps using the CoP tools.

**Comment by erikhjensen** [comment]
Would you like me to close this issue or, will you discuss it further?

**Comment by djdanielsson** [comment]
I will close it and kick off a release soon, if you find you still see issues with that version please open new issues to track those issues.
