### ISSUE TITLE
object_diff role does not account for paginated API responses

### ISSUE THREAD

**Issue by rez-a-bug** [redhat-cop/automate_tower_genie_collections#440]
We need to add "return_all: true" to API queries in object_diff role to ensure all objects are included in the responses.
Currently this is not the case and only the first page of results (25 objects) are returned.

**Comment by silvinux** [comment]
Nice catch!!!. We'll work on this to fix it as soon as possible. Thanks for report it.

**Comment by ivarmu** [comment]
It's been implemented with paginated results (with a limit at the `query_controller_api_max_objects` variable) for the `roles` object type (see #454).

Other object types are still pending to be improved.
