### ISSUE TITLE
Creating Inventory Sources without launching Inventory Sync on them ?

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#465]
Usage Issue

Controller version: 2.2.4

I'm creating a bunch of inventory and associated sources using controller_configuration and since an Inventory Sync is triggered for each Inventory Source that is being added/modified, even for existing Inventory Sources where no modification is applied, it creates a very high load on the executing node.

I was unable to find an option in the source to prevent the Inventory Sync execution.
Is there a mecanism to control this?

**Comment by sean-m-sullivan** [comment]
So how are you calling the collection, are you just using the dispatch role? Each of the roles can be called on their own, the dispatch is just a shorthand way of calling them. 
Right now the inventory source role doesn't trigger a sync, its the inventory_source_update role that runs after it that does. You can customize what order the roles run in, or even just run a few. 

The dispatch role has defaults that can be overriden
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/dispatch/defaults/main.yml

Or you can set it to run a few that are needed
https://github.com/sean-m-sullivan/ee_definition_config/blob/a3f35ad1ae5e02c012bd7bd3f976b407ace4a773/configure_controller_no_survey.yaml#L148

or any other number of ways. Let us know if that helps!

**Comment by nodje** [comment]
Gotcha!
Very clear now.
Plus you gave me the name of the offcial RedHat `infra.controller_configuration` version (which i still can't find searching in RedHat AutomationHub)

**Comment by Tompage1994** [comment]
@nodje, you won't find it in the console.redhat.com Automation Hub. Instead you will find it as part of the validated content pre-loaded into private Automation Hub in AAP 2.3.

See [this blog](https://www.ansible.com/blog/crank-up-your-automation-with-ansible-validated-content) for more detail on how to get this collection (and others) in AH.
