### ISSUE TITLE
Ansible Tower support? awx.awx vs ansible.controller or controller_configuration < 2.0.0?

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#467]
I finally understood the reason for the Warning I kept receiving upon RedHat COP roles execution (~"you are using awx.awx collection").

I got it even though I was providing the collections dedicated to the target platform (ansible.tower & redhat_cop.controller_configuration)

I was using a venv with ansible installed instead of ansible-core only. And the former install with awx.awx collection.

But now that I am using a venv with ansible-core only, object_diff complains in "Check installed collections (block)" that it can't find either ansible.controller nor awx.awx.

I assumed from previous Issue conversations that redhat_cop.controller_configuration was able to detect and use adequate collection (ansible.controller vs ansible.tower) according to the target platform.

Obviously this is not the case.
The only few references of the string "ansible.tower" I can find in the sources of 2.2.4 are mostly in the changelog (Changed all references for ansible.tower to ansible.controller 2.0.0)

Which collection shall I use or shall use controller_configuration < 2.0.0 along with ansible.tower?

**Comment by adonisgarciac** [comment]
You should use the latest version of this collection. I think it is compatible with ansible.tower. This collection doesn't detect the adequate collection, this collection check which collection is installed to use it in filetree_read and object_diff:

https://github.com/redhat-cop/controller_configuration/blob/devel/roles/object_diff/tasks/main.yml#L7-L28
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/filetree_create/tasks/main.yml#L7-L28

**Comment by nodje** [comment]
Sorry I must have been unclear.
My current understanding is:
- provide collection `ansible.tower` to target Ansible Tower
- provide collection `ansible.controller` to target Ansible AP

But as the code you point out to shows, there's no support for the ansible.tower collection (anymore?)

So which collection should I provide to support Ansible Tower?
Ansible controller or awx.awx ?

Or is is even better to use controller_configuration < 2.0.0 ? (before ansible.tower was replaced by ansible.controller as mentioned in the Changelog)

**Comment by adonisgarciac** [comment]
ansible.controller is the new name. They are not different collections:

https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/docs/

Release and Upgrade Notes
Notable releases of the ansible.controller collection:

3.7.0 initial release
4.0.0 ansible.tower renamed to ansible.controller
tower_ prefix is dropped from the module names, e.g. tower_inventory becomes inventory

So if you have a version of ansible.tower installed and it is compatible with the version of your tower, it should work. But now, the collection is named ansible.controller and start in 4.0.0 version.

I would use the same version of your tower for ansible.tower/ansible.controller. I would use the latest version of controller_configuration.

**Comment by nodje** [comment]
I see, thanks.

But I'm unable to follow your advice then, using the same version of Tower target for the collection is not supported by controller_configuration.

My only option is to use the latest version of ansible.controller to target Tower and AAP2x.

**Comment by Tompage1994** [comment]
I think you *should* be able to use the ansible.tower collection (which I think you're still supposed to use against Tower 3.8 etc.) 
You *might* need to use an older version of this collection (e.g. [1.5.1-3.8.3 tower version](https://github.com/redhat-cop/controller_configuration/releases/tag/1.5.1-3.8.3))

A word of warning though that this path hasn't been tested for ~18 months now and we likely won't be able to help too much if things don't work properly with it.

Your other path is to use latest of all the collections and in theory it should work in the most part (albeit you may get warnings). Again, though, this path is not tested and we may not be able to help too much with getting it to work against Tower

**Comment by adonisgarciac** [comment]
> I see, thanks.
> 
> But I'm unable to follow your advice then, using the same version of Tower target for the collection is not supported by controller_configuration.
> 
> My only option is to use the latest version of ansible.controller to target Tower and AAP2x.

I think that latest version of ansible.controller will not have the same parameters than the API of Tower.

**Comment by nodje** [comment]
ok thanks. i'll them stick to latest version as much as possible. hopefully we will have completed our migration towards AAP2 before anything breaks.

And I'll try 1.5.1-3.83 if anything goes wrong.

**Comment by sean-m-sullivan** [comment]
Wanted to weigh in on this, I currently have some People I work with that use awx.awx 21.7.0 and controller configuration 2.1.6, against a Tower 3.8.2 and it works no issues. So that should give you a starting point.
