### ISSUE TITLE
AAP Config as Code Office Hours Agenda - Feb 15th 2023

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#475]
# AAP Config as Code Office Hours
## What

After attending other Office Hours of various groups, we decided to host one of our own. 
The goal is to host a regular time for the AAP Config as Code contributors to be available for your folks in the Community, so we are happy to announce a new regular video meeting.

## Where & When

Our first meeting will be held on Wednesday, Feb 15, 2023 at [1600 UTC](https://dateful.com/time-zone-converter?t=16:00&tz=UTC)

-   [Google Meet](https://meet.google.com/npj-fyzv-oyo)
-   Via Phone PIN: 621 302 239 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held every four weeks, at [1600 UTC](https://dateful.com/time-zone-converter?t=16:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#aap_config_as_code:ansible.com](https://matrix.to/#/#aap_config_as_code:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the quatri-weekly video meeting you can join the Community (inc development team) on Matrix Chat.

- Matrix: [#aap_config_as_code:ansible.com](https://matrix.to/#/#aap_config_as_code:ansible.com) (recomended)

See you soon!

## Links
No previous meeting

**Comment by sean-m-sullivan** [comment]
# First Meeting Intros

- Give folks the chance to say hi
- Say what we are hoping to achieve

**Comment by sean-m-sullivan** [comment]
# Meeting time ???
Is this time good for everyone, should we change it? Right now we know of people in Europe, Pacific, and Eastern Time and this seemed like the best crossover time.

**Comment by bbaassssiiee** [comment]
How can we get the controler_configuration in OpenShift when deploying with Kustomize? i.e. fully gitops.

**Comment by sean-m-sullivan** [comment]
> How can we get the controler_configuration in OpenShift when deploying with Kustomize? i.e. fully gitops.

One could argue that using the Ansible tool to deploy it is gitops. The issue from making it just a definition applied is that the data is stored in a postgres database, so it has to get there somehow, either through awx cli, or the API. We've opted to use tools around the API.

**Comment by djdanielsson** [comment]
So honestly I don't have much experience with OCP but following a gitops mentality once you make a change in git it triggers a CI tool that runs the playbook to apply the configuration. We currently don't have a great way to compare what is currently configured in AAP vs code best to look at filetree read and create roles that are about as good as we can do for the moment.

**Comment by sean-m-sullivan** [comment]
[Meeting recording for those who wish to catch up](https://drive.google.com/file/d/1dBAFgfCZ34pG8wjI7jzZc0WRS1yXYvkT/view?usp=sharing)


Things discussed. 
@bbaassssiiee question
Bot for our matrix room to do announcements and increased privileges for admins
Using the tooling repo to make a site that has the Readmes linked and like a docs site. Jekyll?
Clean up the main readmes in each repo, like EDA did.
Probably more that I didn't jot down.

**Comment by bbaassssiiee** [comment]
https://www.redhat.com/architect/ansible-automation-controller-cac-gitops

**Comment by bbaassssiiee** [comment]
https://github.com/orgs/playingfield/discussions/1
