### ISSUE TITLE
CI breaks because dependent collection not installed

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#490]
# Summary
The pre-commit CI can't find the module on the syntax-check because it's not been installed.

related https://github.com/redhat-cop/ah_configuration/issues/218

# Issue Type

- Bug Report

# STEPS TO REPRODUCE
See https://github.com/redhat-cop/controller_configuration/actions/runs/4112892539/jobs/7098811147

**Comment by sean-m-sullivan** [comment]
Agreed on this, and I just haven't had time to investigate, I was also looking at how to get testing to run on the bot actions, to prevent merging precommit version updates that break tests, which is a permissions/token thing, and likely have an answer, but once again, time.

**Comment by djdanielsson** [comment]
If you look at the other CIs you see that they install ansible-core and then collections but this one just installs ansible and no collections
