### ISSUE TITLE
`TimeoutError The read operation timed out` occurs when attempting to create many objects

### ISSUE THREAD

**Issue by ansiblejunky** [redhat-cop/automate_tower_genie_collections#497]
# Summary

When running the playbook to create objects in AAP Controller using the collection roles, any of the following time out errors can be seen at times when attempting to create/update many objects for a specific object type. In my example where I hit the error, I had 20 credentials. 

```
Failed to get token: The read operation timed out
```
or ...
```
There was an unknown error when trying to connect to https://aap.example.com/api/v2/organizations/?name=generic: TimeoutError The read operation timed out
```
The error occurs on the `infra.controller_configuration.credentials : Configure Controller Credentials | Wait for finish the credential creation` task where it's using the `async_status` module to check on the async job.

After analysis, I determined the root cause. The issue is the following:
- The `credential` task runs to create the credentials asynchronously and sets `async: 1000`
- Then the `async_status` task runs and the timeout occurs, and typically after the first 5 looped items (suggesting an issue with  parallelism here)

So here's the two ways I was able to get around the problem.

- Increasing the `async` to something like 5000 eliminated the problem
- Increase the `forks` from default of 5 to something like 30 (for testing purposes) also avoided the problem 

From [our docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html#asynchronous-ad-hoc-tasks) it does mention this problem:

```
Poll mode is smart so all jobs will be started before polling begins on any machine. Be sure to use a high enough --forks value if you want to get all of your jobs started very quickly. After the time limit (in seconds) runs out (-B), the process on the remote nodes will be terminated.
```

Further notes from that same site states NOT to specify `poll: 0` if later tasks need those resources. So I'm also not sure if we should be using polling or not.
```
Do not specify a poll value of 0 with operations that require exclusive locks (such as yum transactions) if you expect to run other commands later in the playbook against those same resources.

Using a higher value for --forks will result in kicking off asynchronous tasks even faster. This also increases the efficiency of polling.
```

Note that, if I remove the async functionality in the controller_collection for the `credentials` task and remove the async_status task, and run my playbook - it works perfectly every time. I think the problem is not just with credentials objects, but all objects where we leverage the async method.

Lastly, I'm not sure if we use `async_status` we need to additionally run it with mode `cleanup`? 

```
When running with poll: 0, Ansible will not automatically cleanup the async job cache file. You will need to manually clean this up with the [async_status](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/async_status_module.html#async-status-module) module with mode: cleanup.
```

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.14.1]
  config file = /Users/jwadleig/Projects/ansible-onboarding/ansible.cfg
  configured module search path = ['/Users/jwadleig/Projects/ansible-onboarding/content/plugins/modules']
  ansible python module location = /Users/jwadleig/.pyenv/versions/3.10.6/envs/dev/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/jwadleig/Projects/ansible-onboarding/content/collections
  executable location = /Users/jwadleig/.pyenv/versions/dev/bin/ansible
  python version = 3.10.6 (main, Aug  8 2022, 15:11:35) [Clang 12.0.0 (clang-1200.0.31.1)] (/Users/jwadleig/.pyenv/versions/3.10.6/envs/dev/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True

ansible-galaxy collection list
Collection                     Version
------------------------------ -------
ansible.posix                  1.5.1
awx.awx                        21.11.0
community.general              6.3.0
containers.podman              1.10.1
infra.aap_utilities            2.2.3
infra.ah_configuration         1.1.0
infra.controller_configuration 2.2.5
infra.ee_utilities             2.0.6
kubernetes.core                2.4.0

Controller version
4.3.0
```

- ansible installation method: one of source, pip, OS package, EE
pip

# OS / ENVIRONMENT

macOS Ventura 13.1

# Desired Behavior

Playbook creates objects without timeout issues.

# Actual Behavior

See above description

# STEPS TO REPRODUCE

Define at least 20 credentials to be created by the `controller_configuration` collection. 
Run the playbook and watch. Timeout happened every time for me, but on the tasks after loop item 5 (default forks).

**Comment by rez-a-bug** [comment]
We get the same error when running inventory_source_update for 20+ inventories.

**Comment by bagasse** [comment]
Hello,

If this issue is due to too many parallel connections,  using `batch` filter in loops should solve the problem (with a parameter to allow users to change batch size).

eg:

```
"{{ credentials | batch(config_batch_limit) | list }}"
```

But that's not an so easy fix as the today implementation have two loops: one for async tasks and one other for async_status.

**Comment by w4hf** [comment]
Hello team,
As a quick workaround, what do you think about making the async timeout a variable, and not hardcoded to 1000 ?

**Comment by djdanielsson** [comment]
it is a possibility we are still looking into this a bit before we make a decision on what the best solution will be

**Comment by antoinep-rh** [comment]
Let me share what I was able to find while doing some testing.
I have been experimenting with creating a large number of "credentials" and using user/password authentication.
I got various and random errors, on all the API endpoints involved by the collection module (/api/v2/credentials, /api/v2/credential_types, /api/v2/organizations , ... and even /api/v2/tokens).
I have noticed that timeout errors always occur when API request response times are greater than 10 seconds. I could see it by scrutinizing the tower.log file (in DEBUG level).
I think all these requests are made by the code in "controller_api.py", and the "Request" class of the Ansible library "ansible.module_utils.urls". In this class, the default timeout is effectively 10 seconds.
To confirm my assumptions: I increased this timeout to 100 seconds, and I no longer encounter any errors. Also, by passing this timeout to 2 seconds, I encounter a lot of them.

**Comment by ericzolf** [comment]
It sounds like the response time of the controller API increases as we hammer it with more requests, to the point where the delay taken by controller to answer API calls goes above the said 10 seconds. There is a practical limit of 100-300 API calls/second per controller instance (see [API capacity](https://docs.ansible.com/automation-controller/latest/html/administration/performance.html)). Are we anywhere near this limit?

**Comment by sean-m-sullivan** [comment]
in terms of credentials its 4 API calls if org is provided, 3 if not, projects are 3 + 3 notifications + 2 credential options + 1 EE for a total of 9 if all options are set. 
So if you do 20 credentials its 80 api calls itself. a project with cred + ee is 5, so would be 100, its all compounding.

**Comment by sean-m-sullivan** [comment]
Closing this as it has been determined to be a module issue, a fix has been found, is awaiting to be merged upstream
