### ISSUE TITLE
The "users" role should not use the `organization` parameter

### ISSUE THREAD

**Issue by mophahr** [redhat-cop/automate_tower_genie_collections#501]
The task in https://github.com/redhat-cop/controller_configuration/blob/devel/roles/users/tasks/main.yml tries to use the `organization` parameter for the `user` module which isn't supported by the module: `Unsupported parameters for (user) module: organization.`

As a solution, line 15 should be removed.

**Comment by adonisgarciac** [comment]
organization is supported in the module:

https://docs.ansible.com/ansible/latest/collections/awx/awx/user_module.html#parameter-organization
https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/content/module/user/

it was added in 4.2 version. If you are using a previous version, you shouldn't define organization for users and it will not fail.

**Comment by mophahr** [comment]
Thanks for clarifying @adonisgarciac 

I'll close this then.
