### ISSUE TITLE
AAP Config as Code Office Hours Agenda - March 15th 2023

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#519]
# AAP Config as Code Office Hours
## What

After attending other Office Hours of various groups, we decided to host one of our own. 
The goal is to host a regular time for the AAP Config as Code contributors to be available for your folks in the Community, so we are happy to announce a new regular video meeting.

## Where & When

Our first meeting will be held on Wednesday, Feb 15, 2023 at [1600 UTC](https://dateful.com/time-zone-converter?t=16:00&tz=UTC)

-   [Google Meet](https://meet.google.com/npj-fyzv-oyo)
-   Via Phone PIN: 621 302 239 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held every four weeks, at [1600 UTC](https://dateful.com/time-zone-converter?t=16:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#aap_config_as_code:ansible.com](https://matrix.to/#/#aap_config_as_code:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the quatri-weekly video meeting you can join the Community (inc development team) on Matrix Chat.

- Matrix: [#aap_config_as_code:ansible.com](https://matrix.to/#/#aap_config_as_code:ansible.com) (recomended)

See you soon!

## Links
[Feb 15th Meeting 2023](https://github.com/redhat-cop/controller_configuration/issues/475)

**Comment by sean-m-sullivan** [comment]
Things on the Agenda, how should we do versions and breaking changes and how they link up with the AAP version.

**Comment by djdanielsson** [comment]
Reminder once AAP 2.4 releases we will be no longer maintaining the redhat_cop namespace and only updating infra

**Comment by sean-m-sullivan** [comment]
Also debate, Should we get an image for use at 
https://galaxy.ansible.com/infra/

Right now the disembodied ghost is not doing it for me, Thoughts on what we should use? I proposed the Red recycling icon, for sybolizing devops and free, But thats the backup choice.

**Comment by bogdanmuresan** [comment]
Controller roles improvements and issues:
 - https://github.com/redhat-cop/controller_configuration/discussions/539
 - https://github.com/redhat-cop/controller_configuration/discussions/538
 - axw-cli?
 - object diff for roles seems to not actually be working( it's deleting all RBAC in or case)
