### ISSUE TITLE
Default user password

### ISSUE THREAD

**Issue by Klaas-** [redhat-cop/automate_tower_genie_collections#521]
# Summary
I think this is more a discussion than a direct bug, I was using the user role to pre-create social auth users. I was a little surprised it created the users with a default password that is not shown in the readme:
https://github.com/redhat-cop/controller_configuration/blob/78ac33e6daf8d09bf0714fc445a593cf90a5a6ff/roles/users/defaults/main.yml#L6

Readme only shows that the password is empty, which is not correct.
https://github.com/redhat-cop/controller_configuration/blob/78ac33e6daf8d09bf0714fc445a593cf90a5a6ff/roles/users/README.md?plain=1#L62-L63

I think this should be changed, no default password, if someone really wants to set a default password they should do so consciously in their own config. 

# Desired Behavior

I am not sure the desired behavor can be set here, I would say passwordless users should be allowed, especially because they already exist if a social auth user is created by awx through login -- Reference upstream https://github.com/ansible/awx/issues/4486 

# Actual Behavior

Sets a default password when using defaults

**Comment by djdanielsson** [comment]
so there are multiple issues here actually and I will address each of them
1) wanting to be able to create a user without a password
    answer: because of the limitations at the API level this is not possible at this time
2) default password is just change_me
   I agree that we probably shouldn't leave this the way it is currently, I think the only real solution at this point is to make it a required field
3) documentation
  No matter what the documentation needs to be updated to be accurate to whatever the code is doing, in my proposed state would be changing it to required true and still not have a default.

**Comment by Klaas-** [comment]
~~the problem with the password being usable for login while social auth is active seems to be specific to azure ad, but it was already fixed upstream~~ https://github.com/ansible/awx/pull/13491
There still is an issue upstream if a user is pre-created with a password and is then transferred to a social auth user

**Comment by djdanielsson** [comment]
closing because this is a module issue not a role issue
