### ISSUE TITLE
Add the possibility to set setting DEFAULT_EXECUTION_ENVIRONMENT by string

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#531]
using 2.2.5

Currently I get an error message that says this setting expect a PK and not a string.
Would be very handy to be able to set this using the name of an existing EE.

**Comment by sean-m-sullivan** [comment]
Can you give an example of the config that caused this to fail so we can investigate?

**Comment by djdanielsson** [comment]
to be more specific please fill out the bug template as much as possible when submitting a bug, I know it asks for a lot but then it saves us time from having to ask for all the things

**Comment by nodje** [comment]
Here's what I have that causes the failure:

controller_settings:
  - settings:
      TOWER_URL_BASE: "https://s00vl9993310/"
      LOGIN_REDIRECT_OVERRIDE: "/sso/login/saml/?idp=websso-itg.staging.echonet"
      #LOGIN_REDIRECT_OVERRIDE: ""
      DEFAULT_EXECUTION_ENVIRONMENT: "ee-minimal-community.general"  # can't use for now, expect PK value

**Comment by djdanielsson** [comment]
it's expecting the ID number of the EE not the name

**Comment by sean-m-sullivan** [comment]
Yep, settings we don't do the lookup and neither does the module as its so many different settings, I'd suggest the ansible.controller/awx.awx controller lookup plugin to get the ID

**Comment by djdanielsson** [comment]
this is not a bug

**Comment by nodje** [comment]
this is a feature request.
Maybe it's not enabled by the module but it'd be a nice to have feature
