### ISSUE TITLE
filetree_create is missing schedule functionality

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#542]
# Summary
filetree_create is missing schedule functionality

# Issue Type

- Bug Report
- Missing functionality

# Expectation
To be able to 'export' schedules when running the filetree_create role. The filetree_read role already allows schedules to be read.

**Comment by drshawnkwang** [comment]
Thanks Tom for creating this issue. 

FTR: `awx export` for a schedule works well. And filetree_create + dispatch does read in the schedules that `awx export` creates without issue.

**Comment by repcsi** [comment]
Hello,

When can I expect this change to be in infra.controller_configuration? 2.4.0 is still missing the schedules. I'm using infra/controller_config

By the way what's the difference between:
https://galaxy.ansible.com/redhat_cop/controller_configuration
and 
https://galaxy.ansible.com/infra/controller_configuration ?
Seems like the redhat_cop one is lagging behind in version quite a bit despite having way more download hits.
