### ISSUE TITLE
How to get the client_secret_id for application.yml objection creation

### ISSUE THREAD

**Issue by sudhann92** [redhat-cop/automate_tower_genie_collections#580]
In application yaml we can able to create the application object in anisble platform but normally when we created same in GUI method we will get client_secret_id during the application creation even that value will show one time only.

From code end how to get that value  or after creation whether any possible to retrieve that client_sceret_id from ansible platform.

**Comment by sean-m-sullivan** [comment]
I am not sure, these are roles implementing the awx.awx/ansible.controller modules, They then interact with the API it should show up in the results:
https://docs.ansible.com/automation-controller/latest/html/controllerapi/api_ref.html#/Authentication/Authentication_applications_create_0

**Comment by sudhann92** [comment]
Yeah i tried to used same role also ... I can able to create the application object but am not able to get the client_secret_id value from the output 

But if your are same thing directly by using REST API POST method in that output you can see the client_secret_id. I guess this kind of bug or need to improve the application role feature to get that value also other wise there is no use of this role.

**Comment by djdanielsson** [comment]
I would try using the module directly if you still see an issue report it on the awx.awx repo because we just utilize their modules and do not maintain them

**Comment by djdanielsson** [comment]
closing because this appears to be a module issue not a role issue
