### ISSUE TITLE
AAP Config as Code Office Hours Agenda - May 11th 2023

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#596]
# AAP Config as Code Office Hours
## What

After attending other Office Hours of various groups, we decided to host one of our own. 
The goal is to host a regular time for the AAP Config as Code contributors to be available for your folks in the Community, so we are happy to announce a new regular video meeting.

## Where & When

The meeting will be held on Thursday, May 11, 2023 at [1300 UTC](https://dateful.com/time-zone-converter?t=13:00&tz=UTC)

-   [Google Meet](https://meet.google.com/npj-fyzv-oyo)
-   Via Phone PIN: 621 302 239 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held every four weeks, at [1300 UTC](https://dateful.com/time-zone-converter?t=13:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#aap_config_as_code:ansible.com](https://matrix.to/#/#aap_config_as_code:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the quatri-weekly video meeting you can join the Community (inc development team) on Matrix Chat.

- Matrix: [#aap_config_as_code:ansible.com](https://matrix.to/#/#aap_config_as_code:ansible.com) (recomended)

See you soon!

## Links
[Feb 15th Meeting 2023](https://github.com/redhat-cop/controller_configuration/issues/475)
[April 12th Meeting 2023](https://github.com/redhat-cop/controller_configuration/issues/568)

**Comment by sean-m-sullivan** [comment]
Topics Quick overview of major changes in the past month
- [The enforce default options Additions](https://github.com/redhat-cop/controller_configuration/issues/495)
- [Export differential module new and improved](https://github.com/redhat-cop/controller_configuration/pull/583)

**Comment by sean-m-sullivan** [comment]
How does everyone feel about the time change

**Comment by sean-m-sullivan** [comment]
One thing we are interested in feedback on, Is we plan this release to be the last one in the redhat_cop namespace, have warnings on the last releases under that namespace to move to infra, and going forward to only release under infra.

**Comment by djdanielsson** [comment]
And if there is anything missing that needs to be added/fixed before doing another release across all collections

**Comment by Klaas-** [comment]
Question for discussion: do you want the collections to be installable from git? Adding a simple templated galaxy.yml could be enough: https://github.com/Klaas-/controller_configuration/blob/klaas-ansible-galaxy-git/galaxy.yml

Maybe we even automatically update this file after a release with the +1 version -- or append a .1 or -dev to the current version to signal this is from git
I've checked some other collections, they either don't do that or use some kind of newer/dev indicator.
https://github.com/ansible-collections/community.general/blob/main/galaxy.yml
https://github.com/ansible-collections/cisco.ios/blob/main/galaxy.yml
https://github.com/ansible-collections/community.aws/blob/main/galaxy.yml

**Comment by sean-m-sullivan** [comment]
@Klaas- After internal discussion we agreed, and next release which should be Soon™ , it will add the latest galaxy file
https://github.com/redhat-cop/ansible_collections_tooling/pull/23
