### ISSUE TITLE
`object_diff` role doesn't support TOWER_x en var for authentication

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#626]
Tested version: 2.3.1

See https://github.com/redhat-cop/controller_configuration/issues/619

Also even if `controller_hostname, controller_oauthtoken, controller_validate_certs` are provided, in some situation `controller_username` can also be expected. 

```
TASK [redhat_cop.controller_configuration.object_diff : Get the current controller user to determine if it is super-admin] ***
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'controller_username' is undefined. 'controller_username' is undefined\n\nThe error appears to be in '/runner/requirements_collections/ansible_collections/redhat_cop/controller_configuration/roles/object_diff/tasks/teams.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: \"Get the current controller user to determine if it is super-admin\"\n  ^ here\n"}
```
It should be possible to get the user corresponding to the provided oauthtoken from the EP `api/v2/me`

**Comment by adonisgarciac** [comment]
Can you try to define the variable?:

```
    controller_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
```

**Comment by nodje** [comment]
Hi Adonis,

I sure can but I haven't defined CONTROLLER_USERNAME as I use an oauth_token for authentification.

I think it's an issue to have to define both.
The default behaviour of ansible.controller is to be able to pick whichever comes, controller_oauthotken OR controller_username+controller_password

**Comment by adonisgarciac** [comment]
I think this issue can be closed. @djdanielsson @sean-m-sullivan
