### ISSUE TITLE
filetree_create not capturing ask_credential_on_launch for Job Templates

### ISSUE THREAD

**Issue by the-it-jaeger** [redhat-cop/automate_tower_genie_collections#628]
# Summary

Running the latest version of filetree_create (as of today) is not capturing `ask_credential_on_launch` for Job Templates.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

ansible --version

```
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/.../.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

ansible-galaxy collection list
```
Collection                     Version
------------------------------ -------
ansible.controller             4.3.0
awx.awx                        21.10.2
infra.controller_configuration 2.4.0
```

Controller is Ansible Automation Platform Controller 4.3.9 running on OpenShift 4.12 installed via Operator.

Ansible installation method: OS package

# OS / ENVIRONMENT

Running infra.controller_configuration collection on RHEL 8.8 VM

# Desired Behavior

I would like the output in `/tmp/filetree_output/<org>/job_templates/*.yml` files to include `ask_credential_on_launch: "True"` when the checkbox is selected in a Job Template on Controller.

# Actual Behavior

The output in `/tmp/filetree_output/<org>/job_templates/*.yml` files **does not** contain `ask_credential_on_launch: "True"` when the checkbox is selected in a Job Template on Controller.

Prompt on launch is selected:

![image](https://github.com/redhat-cop/controller_configuration/assets/61639149/e4bdd944-9bb5-4072-a718-78aae285b545)

ask_credential_on_launch is not reflected here:

![image](https://github.com/redhat-cop/controller_configuration/assets/61639149/e013ac80-2076-454f-bd07-a1c3e19c9ec9)

**Comment by ivarmu** [comment]
Thanks @the-it-jaeger for reporting this. I've added all the Job Template's fields to the generated output, so if they have any content at the Tower/AAP, they will be populated at the output files as well.
