### ISSUE TITLE
How to resolve Organization<->Credential dependency cyle?

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#629]
I'm stuck during my CASC playbook initial execution as my Organizations need galaxy_credentials to have access to AH, and Credentials need to be  created within an existing Organization.

After initial execution, when ran in an idempotent mode, Organization already exists and all is fine.

But I need to CI this CASC and anyway will need to be able to boostrap a new AAP instance with this CASC.

Short of running 2 cycles of filetree_read/dispatch I don't see what else could be done.

**Comment by djdanielsson** [comment]
how to do this with file tree_read and dispatch idk but if you look at my template repo you can see how I handle this https://github.com/redhat-cop/aap_configuration_template

**Comment by adonisgarciac** [comment]
The last version of dispatch role should address this issue:

https://github.com/redhat-cop/controller_configuration/blob/devel/roles/dispatch/tasks/main.yml

It has a first task where everything is configured without galaxy_credentials and a second task where organizations are configured with galaxy_credentials.

**Comment by nodje** [comment]
Thanks,

for the record use

```
ansible.builtin.include_role:
        name: infra.controller_configuration.organizations
      vars:
        assign_galaxy_credentials_to_org: false
        assign_default_ee_to_org: false
```
provided by 
https://github.com/redhat-cop/controller_configuration/tree/devel/roles/organizations

and taken into account by dispatch and organization role
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/organizations/tasks/main.yml
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/dispatch/tasks/main.yml

I get that the organizations/tasks/main.yml will not look for creds and EE upon creation, so I can dispatch Organization first using this 2 settings.

But how are the creds and EE going to be assigned to the Organization upon creation then?

**Comment by adonisgarciac** [comment]
It is necessary to launch twice the role organizations. First without galaxy creds and EE and second time with them. The dispatch role already do this.

In fact, Orgs are created at first execution but you need to launch again to assign galaxy creds and EE. If you are using the dispatch role, you don't need to care about it.

**Comment by nodje** [comment]
Hi @adonisgarciac,

there must be something wrong with dispatch's second pass on organization: 
I'm using the filetree_read then the dispatch role, and yes as you mentioned, my playbook do run the dispatch task "name: Include Tasks to add Galaxy credentials and Execution Environments to Organizations" but no EE or Galaxy cred gets attached.

My playbook basically is:
```
    - role: redhat_cop.controller_configuration.filetree_read
    #- role: redhat_cop.controller_configuration.object_diff
    - role: redhat_cop.controller_configuration.dispatch
      vars:
        assign_galaxy_credentials_to_org: false
        assign_default_ee_to_org: false
```


I'm using 2.3.1.


Here's an exec output sample on a fresh AAP2 instance: 
(but same behaviour on all my instances. The tasks runs by Galaxy creds and EE don't get assigned)
```
TASK [redhat_cop.controller_configuration.organizations : Configure Controller Organizations | Wait for finish the organization creation] ***
{
  "started": 1,
  "finished": 1,
  "stdout": "",
  "stderr": "",
  "stdout_lines": [],
  "stderr_lines": [],
  "ansible_job_id": "790739762188.8696",
  "results_file": "/tmp/.ansible_async/790739762188.8696",
  "changed": false,
  "id": 1,
  "invocation": {
    "module_args": {
      "name": "BP2I CS22B - OS Linux MEO MOE",
      "description": "Super Admin Linux AAP Organization",
      "instance_groups": [
        "default"
      ],
      "state": "present",
      "controller_host": "https://aap2-ci-test-linux-automation.apps.oc001b000001.fr.net.intra",
      "validate_certs": false,
      "controller_username": "admin",
      "controller_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "controller_oauthtoken": "",
      "max_hosts": 0,
      "controller_config_file": null,
      "new_name": null,
      "default_environment": null,
      "custom_virtualenv": null,
      "notification_templates_started": null,
      "notification_templates_success": null,
      "notification_templates_error": null,
      "notification_templates_approvals": null,
      "galaxy_credentials": null
    }
  },
  "warnings": [
    "You are running collection version 4.3.0 but connecting to Red Hat Ansible Automation Platform version 4.2.1"
  ],
  "_ansible_no_log": false,
  "attempts": 1,
  "__organizations_job_async_results_item": {
    "failed": 0,
    "started": 1,
    "finished": 0,
    "ansible_job_id": "790739762188.8696",
    "results_file": "/tmp/.ansible_async/790739762188.8696",
    "changed": false,
    "__controller_organizations_item": {
      "name": "BP2I CS22B - OS Linux MEO MOE",
      "description": "Super Admin Linux AAP Organization",
      "instance_groups": [
        "default"
      ],
      "default_environment": "TEST ee-minimal-community.general",
      "galaxy_credentials": [
        "TEST Automation Hub Community Repository",
        "TEST Automation Hub Published Repository",
        "TEST Automation Hub RH Certified Repository",
        "TEST Automation Hub Validated Repository"
      ]
    },
    "ansible_loop_var": "__controller_organizations_item"
  },
  "ansible_loop_var": "__organizations_job_async_results_item",
  "_ansible_item_label": {
    "failed": 0,
    "started": 1,
    "finished": 0,
    "ansible_job_id": "790739762188.8696",
    "results_file": "/tmp/.ansible_async/790739762188.8696",
    "changed": false,
    "__controller_organizations_item": {
      "name": "BP2I CS22B - OS Linux MEO MOE",
      "description": "Super Admin Linux AAP Organization",
      "instance_groups": [
        "default"
      ],
      "default_environment": "TEST ee-minimal-community.general",
      "galaxy_credentials": [
        "TEST Automation Hub Community Repository",
        "TEST Automation Hub Published Repository",
        "TEST Automation Hub RH Certified Repository",
        "TEST Automation Hub Validated Repository"
      ]
    },
    "ansible_loop_var": "__controller_organizations_item"
  }
}
```

But orga `Provisioning` here doesn't get any EE or Galaxy Creds.

This is the last task of the playbook, and it's in OK, instead of Changed, so I guess it determines that nothing has to be done for some reason.

**Comment by adonisgarciac** [comment]
It is because you are setting:
```
     vars:
        assign_galaxy_credentials_to_org: false
        assign_default_ee_to_org: false
```
You don't have to do it since it was set in the role:

https://github.com/redhat-cop/controller_configuration/blob/devel/roles/dispatch/tasks/main.yml#L13-L14

**Comment by nodje** [comment]
Hi Adonis,

it does work as expected on a fresh instance when I remove the vars I have assigned, as you explained.

However, I can't get it to work on an instance where the Organizations already exist and have a different sets of Galaxy Creds than what the dispatch role is supposed to apply. 

```
[...]

TASK [Include Tasks to add Galaxy credentials and Execution Environments to Organizations] ****************************************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/redhat_cop/controller_configuration/roles/dispatch/tasks/main.yml:16

TASK [redhat_cop.controller_configuration.organizations : Validating arguments against arg spec 'main' - An Ansible Role to create organizations on Ansible Controller.] **********************************************************
task path: /root/project/ansible/tower/automation-admin/playbook.yml:2
ok: [localhost] => {"changed": false, "msg": "The arg spec validation passed", "validate_args_context": {"argument_spec_name": "main", "name": "organizations", "path": "/root/.ansible/collections/ansible_collections/redhat_cop/controller_configuration/roles/organizations", "type": "role"}}

TASK [redhat_cop.controller_configuration.organizations : Add organizations] ******************************************************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/redhat_cop/controller_configuration/roles/organizations/tasks/main.yml:2
skipping: [localhost] => {"changed": false, "skipped_reason": "No items in the list"}

TASK [redhat_cop.controller_configuration.organizations : Configure Controller Organizations | Wait for finish the organization creation] *****************************************************************************************
task path: /root/.ansible/collections/ansible_collections/redhat_cop/controller_configuration/roles/organizations/tasks/main.yml:35
skipping: [localhost] => {"changed": false, "skipped_reason": "No items in the list"}

PLAY RECAP ************************************************************************************************************************************************************************************************************************
localhost                  : ok=149  changed=4    unreachable=0    failed=0    skipped=59   rescued=0    ignored=0 
```

For some reasons it doesn't find any Organization to process ("No item in the list")

Not too sure where to go from there as the same playbook works for a fresh instance as I was saying.

**Comment by adonisgarciac** [comment]
I've tested it and it works as expected. So, I'm not sure what are you doing to get that situation. 

Can you launch the same in verbose mode? It seems the problem come from some previous task (something managing the variables or similar..) But I've changed the galaxy credentials manually and launch the config playbook and it has set again the good credentials.

**Comment by nodje** [comment]
I got it.
I had an issue on variables not being set correctly in organization _controller. 
The `instance_groups: "{{ common_instance_groups }}"` var was not correctly set.


It happened to me a  times on some controllers already by now.

The tasks
`Get the list of files` and `Read Definitions` are always performed correctly but when `Populate the list` is empty it shows something is wrong in the controller variable definition.

It'd be nice to be able to report on this type of problem more clearly.
