### ISSUE TITLE
filetree_create is creating empty files

### ISSUE THREAD

**Issue by ivarmu** [redhat-cop/automate_tower_genie_collections#632]
# Summary

The `filetree_create` role is creating empty files when there are no objects to be exported

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

Without explicit details by now.

# OS / ENVIRONMENT

# Desired Behavior

The role shouldn't create empty files if there's no content to be populated

# Actual Behavior
The role is creating empty files when no content is received from the API

No more information by now.

# STEPS TO REPRODUCE

Not reproduced by now.

**Comment by rhklaus** [comment]
To reproduce this, create a user who has no permissions.  We were able to successfully perform an import, by deleting the empty file created by filetree_create for that user.

**Comment by rhklaus** [comment]
For reference, here is what the file contents were that caused the import failure:

---
controller_roles:

**Comment by ivarmu** [comment]
Hi @rhklaus, I've been trying to reproduce it, but not been able to. I've created a user with no permissions, and, at minimum, it must belong to an organization. If I remove that membership, the API roles for that user are empty, and the user is not exported at all, as it is neither useful at all:

![image](https://github.com/redhat-cop/controller_configuration/assets/26822043/f33df30b-593f-4465-b396-8c71b419073c)

If I leave the minimum user's roles (organization membership), the generated files has the correct contents:
```
~/tmp/Ansible $ cat /tmp/filetree_output/user_roles/current_roles_noperms.yaml
---
controller_roles:
  - user: "noperms"
    organizations:
      - "Default"
    role: "member"
...
~/tmp/Ansible $ cat /tmp/filetree_output/Default/users/noperms.yaml

---
controller_user_accounts:
- username: "noperms"
  password: "INITIAL"
  email: ""
  first_name: "noperms"
  last_name: ""
  auditor: "False"
  superuser: "False"
  update_secrets: False
...
~/tmp/Ansible $ 
```

Please, could you confirm the problem persists in your case? If not we could close that issue.

**Comment by ivarmu** [comment]
Consulted with @rhklaus and closing the issue as it has not been reproduced at all.
