### ISSUE TITLE
Bug: controller_export_diff credentials comparison is broken in awxkit 22.4.0

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#639]
# Summary

Bug: controller_export_diff credentials comparison is broken in awxkit 22.4.0
only the credentials comparision is broken, the rest works. It is not populating the organization field as intended.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details
Failed to export assets organization with resource { credential data here}

Fix is currently to downgrade to awxkit 22.3.0
pip install awxkit=22.3.0

**Comment by djdanielsson** [comment]
is this still a bug?

**Comment by aoyawale** [comment]
I believe this was fixed in previous versions of the awxkit.
