### ISSUE TITLE
Custom Credential Type formatting

### ISSUE THREAD

**Issue by weiyentan** [redhat-cop/automate_tower_genie_collections#67]
Hi there,

In the documentation for Custom Credential Type it mentions something about the formatting of jinja and the injectors. Here is a sample of my injector for a custom credential that I am testing out as per the example.

https://gist.github.com/weiyentan/a1dbf3e384fa19d239083bc7415b18d1

What I am finding is that when I am running the code on AWX ...v12 I am seeing it in the custom credential type like this:

https://gist.github.com/weiyentan/8210e56c09c9e6ace37ea954293a354b

Any help or clarity would be most welcome. Many thanks on this great collection.

**Comment by weiyentan** [comment]
looks like after a bit of massaging on the data structure that i wrote it looks like it has the outcome that I was looking for. Many thanks. I'll be closing this issue.

**Comment by sean-m-sullivan** [comment]
Had been looking at this, Do you think we need to update the Readme to be more explicit about the double space format?

Back when I was developing this I found the single space had issues, but the double space worked as nothing else is normally double spaced. Noticed your first example was single spaced gap between the curly brackets.

**Comment by weiyentan** [comment]
I think it woud have more clarity on what to type.

I read the explanation on what needs to be written but the example showed
what it should look like.

It was a bit confusing as to what I was supposed to write. So i had to test
a few things before i got it right.
