### ISSUE TITLE
Role tower_credential_input_sources should not have a default set.

### ISSUE THREAD

**Issue by spyrexd** [redhat-cop/automate_tower_genie_collections#68]
The tower_credential_input_sources role has a default var `tower_credential_input_sources` set as an example. This causes the role to always be run when setting a conditional on the role as in the example playbooks.

This snippet will never be skipped.
```yaml
roles:  
   - {role: credential_input_sources, when: tower_credential_input_sources is defined, tags: credential_input_sources}
```

**Comment by Tompage1994** [comment]
I'll use this issue to track comments for other issues raised related to this: #69 #70 #71.

This issue occurs on:
- credential_input_sources
- credential_types
- credentials
- groups
- hosts
- job_templates
- notifications
- organizations
- projects
- schedules
- tower_role
- users
- workflow_job_templates

The roles which do not have a default (and it would be sensible to do so) are:
- inventories
- inventory_sources
- labels
- teams

I'm leaning towards taking out the defaults and I will create a PR for this as the examples are in the README for each role (I will double check there is an example in each role)
