### ISSUE TITLE
Wrong default value for workflow_job_templates limit

### ISSUE THREAD

**Issue by bogdanmuresan** [redhat-cop/automate_tower_genie_collections#724]
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/workflow_job_templates/tasks/main.yml#L13

Default value set for workflow templates limit is 0, but I think this should be empty string.

**Comment by sean-m-sullivan** [comment]
it should match this as empty string, yes
https://github.com/redhat-cop/controller_configuration/blob/a79f987765ae7d6ba5763c6d45c56ea7d325ec3f/roles/job_templates/tasks/main.yml#L17C145-L17C145

Funnily enough the job template api/v2/job_templates OPTIONS lists it as "", however workflow_job_template OPTIONS lists it as null.

**Comment by ivarmu** [comment]
This issue should be resolved as the #729 had been merged, shouldn't it?
