### ISSUE TITLE
Update project sync time to be 60s, by increasing delay to 2.

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/automate_tower_genie_collections#736]
Update project sync time to be 60s, by increasing delay to 2.

Many projects with collection requirements take longer then 30 seconds, we shall increase the delay by to 2 to double the time it takes to 60s

https://github.com/redhat-cop/controller_configuration/blob/af03e7842e3ef966f60f54ad72cc1efbbbd8774d/roles/projects/defaults/main.yml#L6C12-L6C12

**Comment by heatmiser** [comment]
Thank you @sean-m-sullivan

**Comment by djdanielsson** [comment]
can this be closed?
