### ISSUE TITLE
No consistency between `README.md`, `meta/argument_specs.yml`, and `defaults/main.yml` in filetree_read role

### ISSUE THREAD

**Issue by akira6592** [redhat-cop/automate_tower_genie_collections#759]
# Summary

There appears to be no consistency between `README.md`, `meta/argument_specs.yml`, and `defaults/main.yml` in filetree_read role.

| | `README.md` | `meta/argument_specs.yml` | `defaults/main.yml` |
|--|--|--|--|
| Required options |All options are required except `controller_location` | Only `org` and `dir_orgs_vars` are required | - |
| Default values |  Default value of `orgs` is `Acme`. Default value of `dir_orgs_vars ` is `orgs_vars `. | `orgs` and `dir_orgs_vars` are have no default value. Because they are required #551 | Default value of `orgs` is `Acme`. Default value of `dir_orgs_vars ` is `orgs_vars` | 

# Issue Type

- Bug Report (Docs)

# Ansible, Collection, Controller details

N/A (Document only)

# OS / ENVIRONMENT

N/A (Document only)

# Desired Behavior

N/A (Document only)

# Actual Behavior

N/A (Document only)

# STEPS TO REPRODUCE

N/A (Document only)

**Comment by akira6592** [comment]
I think `meta/argument_specs.yml` is correct.

**Comment by Tompage1994** [comment]
I believe you're right that the argument spec will be the correct one as it will be doing the checking when ran anyway. 

perhaps the Iberian guys who maintain this role can comment?

CC @adonisgarciac @silvinux @ivarmu

**Comment by ivarmu** [comment]
Thanks a lot @akira6592 for opening this PR. I agree with you guys. I'm correcting it.

**Comment by akira6592** [comment]
Thank you for your comments.

@ivarmu 

>I'm correcting it.

Thank you!

**Comment by akira6592** [comment]
Thank you for fixing!
