### ISSUE TITLE
Dispatch: Unable to create organisation and notification template in the same run

### ISSUE THREAD

**Issue by jon4hz** [redhat-cop/automate_tower_genie_collections#765]
# Summary

As the title says, currently it's impossible to create a notification template and an organization in one run. It's a similar chick egg situation as with the galaxy credentials. It could be solved by introducing an `assign_notification_templates_xxxxx_to_org`.

What do you think about that?

**Comment by djdanielsson** [comment]
I personally do not use dispatch so I would have to look into this a bit more, we may need to create another option like we had to do for creds and have it skip assigning them until after the organization is created then you create the notifications and then re-run the organization to add in the notifications
