### ISSUE TITLE
Document the destroy_current_nodes option

### ISSUE THREAD

**Issue by kbreit-insight** [redhat-cop/automate_tower_genie_collections#776]
# Summary

The workflow role has `destroy_current_nodes` as an option but there are no examples to show how to use it. The type is shown as `dict` which is a little curious considering I think the module is a boolean.

https://github.com/redhat-cop/controller_configuration/tree/devel/roles/workflow_job_templates is the link to the role documentation and https://github.com/ansible/awx/blob/b7b7bfa520780c481046581f2ce9c38ccc6bc1d8/awx_collection/plugins/modules/workflow_job_template.py#L432 is a link to the module arg documentation.

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

```console (paste below)
ansible --version

ansible-galaxy collection list

Controller version

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

# Desired Behavior

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)

```

# STEPS TO REPRODUCE

```yaml (playbook/task)

```

```yaml (config/list/array/variables)

```

**Comment by sean-m-sullivan** [comment]
It should be bool, not sure that typo got in, as I wrote both >< , needs a pr to fix
