### ISSUE TITLE
Should filetree_create export the credential with '$encrypted$' instead of ''?

### ISSUE THREAD

**Issue by ecchong** [redhat-cop/automate_tower_genie_collections#788]
### Discussed in https://github.com/redhat-cop/controller_configuration/discussions/786

<div type='discussions-op-text'>

<sup>Originally posted by **ecchong** March 18, 2024</sup>
Why are we replacing the '$encrypted$' string for password with '' empty string in filetree_create template 
 [current_credentials.j2](https://github.com/redhat-cop/controller_configuration/blob/1217522ee9078b6e9a65e6d6e271f2592f248c5b/roles/filetree_create/templates/current_credentials.j2#L15)? 

When importing the credential back into AAP, the '' causes the password to be overwritten with an empty string instead of being ignored when it sees '$encrypted$' string.
</div>

**Comment by ivarmu** [comment]
Hi @ecchong. Thanks a lot for raising this. Sincerely, I didn't thought so much about this when coded that line... so, if it's demonstrated that leaving `$encrypted$` is better, I'll agree on changing it, but take in care that the objective of the `filetree_create` role is to give you a base to have your configuration as code, both as a migration strategy and as a start point of managing your AWX/Tower/Controller using CasC, so the sensitive parts of these exported credentials is supposed to be written down into the generated files as a vaulted values.

**Comment by ecchong** [comment]
Maybe we can have an option to allow leaving the `$encrypted$` text in the files.  I believe the API will leave the password value unchanged when it sees `$encrypted$`.  If user want to replace it with vaulted string, they can still do that.  The problem of leaving it as '' is that it will break existing credential, if user just upload the configuration as is.

This should be an easy fix in the Jinja2 file.  I will create a PR.
