### ISSUE TITLE
updating organisation name 

### ISSUE THREAD

**Issue by mondherGL** [redhat-cop/automate_tower_genie_collections#793]
Hello , 

i want to  rename existing organisation to keep existing objects, is it possible to rename organisation using controller_configuration version 2.3.0 ( redhat) ?

Thank you in advance,

**Comment by djdanielsson** [comment]
So I have quite a few questions here, 1) why do you want to do it with code specifically? 2) when you are talking about controller_configuration version 2.3.0, you are talking about the collection version not AAP version correct? if so why that specific version? 3) what version of controller? 4) what version of awx.awx or ansible.controller?

**Comment by mondherGL** [comment]
Hello ,

1) why do you want to do it with code specifically?
i have several environments , and i am using code to automate updates . 
i am getting organisations names from SAML mapping so in case of SAML updates i can update automatically my objects under AAP including organisations names

2) when you are talking about controller_configuration version 2.3.0, you are talking about the collection version not AAP version correct?
yes i am talking about the collection version because i am using this version on my code ( this is the last version available on my private automationHub ) 

 3) what version of controller?
AAP controller version is 4.5.1  

4) what version of awx.awx or ansible.controller?
ansible.controller version 4.5.0

Regards,
Mondher

**Comment by djdanielsson** [comment]
2.3.0 is about a year old. you should sync validated content or add it to your community repo list to sync the latest content. if for some reason your organization does not allow for you to sync directly from console.redhat.com then I would manually pull it down and upload it into your hub. I just merged the ability to rename an organization though so it is not even in the 2.7.1 release. I am not sure how easily it will be for you to set it up to know the old name and new name with SAML in a way that you are not manually updating it.

**Comment by nodje** [comment]
I think what's missing even in 2.7.1 is a way to declaratively update an existing Orga's name.
This is typically available for resources like Credential or Group through the `new_name` parameter.

**Comment by djdanielsson** [comment]
yes I said that in my last comment that I just merged #795 which added that functionality but still running a year old version of the collection will be missing a lot of other features and fixes let alone if running that old of one makes me doubt that when the next release happens that they will get the latest version and be able to use the feature they are asking for

**Comment by ivarmu** [comment]
In addition, and to facilitate the management of your configuration as code, the PR #784 has been merged and provides a playbook to rename an object massively (wich can be an organization, so it can be renamed both at the organization definition itself and at all the objects belonging to that organization) and another one to set a specific organization name to all the objects defined into a given path.

**Comment by nodje** [comment]
> yes I said that in my last comment that I just merged #795 which added that functionality but still running a year old version of the collection will be missing a lot of other features and fixes let alone if running that old of one makes me doubt that when the next release happens that they will get the latest version and be able to use the feature they are asking for

Sorry @djdanielsson, didn't fully read your post :| my bad.
It's great 👍 
Can we expect it to be merged into 2.7.2 ?

How does these rename behave in terms of idempotency?
Can these tasks ran a second time after the initial rename?

**Comment by nodje** [comment]
> In addition, and to facilitate the management of your configuration as code, the PR #784 has been merged and provides a playbook to rename an object massively (wich can be an organization, so it can be renamed both at the organization definition itself and at all the objects belonging to that organization) and another one to set a specific organization name to all the objects defined into a given path.

thanks for this info @ivarmu 

It could be useful.
Though, I feel that such a feature should be provided by any good IDE

Admittedly, mine doesn't provide it (Intellij IDE Community with https://plugins.jetbrains.com/plugin/14893-ansible plugin).
I'm not sure if the payed edition or VSCode can support that.

**Comment by nbetmo** [comment]
test

**Comment by mondherGL** [comment]
Hello , 

after using the new attribute new_name , we can rename organiszations and teams , the problem is that our playbook is no mor idempotent ( playbook crach when it trying to rename an already renamed orga )  .

Thank you in advance,

**Comment by djdanielsson** [comment]
once you rename you should remove the old name and update to the new name

**Comment by skynetmo** [comment]
Hello,

In this case it would just let us to avoid the re-creation of objects with new names and the deletion of old ones.
So, It's just a renaming of objects in one shot as the code is not idempotent.

Is there any way how to rename objects in idempotent manner ? many thanks.
 
 BR.

**Comment by ivarmu** [comment]
You can use the `object_diff` role for that purpose.

**Comment by djdanielsson** [comment]
The action is a onetime event I do not understand why you would expect this to be idempotent? And I fail to see how object_diff would make this operation idempotent as well? Unless you are talking about actually deleting the old objects and recreating them which I do not believe was the objective.

**Comment by nodje** [comment]
Well, this collection is made for Infra as Code, so a common use case is to have a playbook based on this collection that configure a target AAP2 env to a desired state.

If you code a renaming, you of course expect the playbook to still be able to run after the renaming, even if oddly the renaming is effectively 'dead code' and doesn't apply anymore. 
At least a renaming on a non existent object should not throw an error IMHO.

**Comment by djdanielsson** [comment]
then you should look at using something like object_diff to delete old objects and create new ones based off code instead of renaming. renaming is for people who value the connections that objects make internally and do not want to break those. also how would you propose to do what you suggest? how does the code know that it has renamed it already or if you typo'd something? if it cannot do the action or validate that it has been done then yes it should fail, and how would it know that it has been done if the objects name is no longer what it was?

**Comment by nodje** [comment]
An existing Organization in use cannot be deleted, otherwise users would lose their resources. `object_diff` would not be a good solution for this. A rename is necessary.

But there may not be a good solution for this to be idempotent.

But it's clearly a specific usage that is not idempotent in a collection that generally is.
A playbook aiming at configuring an AAP2 instance has to be idempotent. 
Having to remove a configuration after an execution is not an option in a multi-env/aap2-instance environment.
As the commit waiting to be pushed to PROD containing the rename would block all executions on other branch. 
(not sure I make myself clear enough here, hope you can see what I mean)

In any case, to be able to use this one-shot renaming config as is, I see the need for a specific supporting system.
An extra bit of configuration that would be `one_shot_addon` labelled, located in a specific branch or activated with an extra var in the main playbook...

**Comment by ivarmu** [comment]
Keep in mind that the rename operation itself is not idempotent, so anything related to that operation can't be idempotent as well. The only thing I can think of is to skip the task if the original name doesn't exist in the AAP, which implies a previous query to the AAP instance to gather that information.

**Comment by nodje** [comment]
Maybe skipping when target object doesn't exist should be the default behaviour for a rename.
Maybe there should be an additional role to perform this, on top of the 4 existing ones, since this would be hard to implement based on the presence of the `new_name` attrtibute.
