### ISSUE TITLE
Controller group is removing/trying to remove constructed inventory groups

### ISSUE THREAD

**Issue by bogdanmuresan** [redhat-cop/automate_tower_genie_collections#798]
# Summary

Same issue that happened with hosts, this time for groups (for hosts it works fine).

Hosts issue:
https://github.com/redhat-cop/controller_configuration/issues/743

I guess the same fix from PR747: 
https://github.com/redhat-cop/controller_configuration/pull/747/files#diff-cf775aa45cd2bafbffb08da0d23b365cbf9a54a74fc9c20679528e211659ed0bR17 

Needs to be applied to groups:
https://github.com/redhat-cop/controller_configuration/blob/devel/roles/object_diff/tasks/groups.yml#L16

# Issue Type

- Bug Report

**Comment by Tompage1994** [comment]
@ivarmu fixed the previous issue with #747

**Comment by bogdanmuresan** [comment]
PR here: https://github.com/redhat-cop/controller_configuration/pull/827
