### ISSUE TITLE
Verbosity on job template not changing back to 0 from higher values and state comes as OK

### ISSUE THREAD

**Issue by gokulan-g** [redhat-cop/automate_tower_genie_collections#801]
# Summary

Using the role from this repo to create job templates using yml files, everything is working good except the job template verbosity is not changing to 0 from higher values, but i'm able to change to any (1..4) values other than 0

# Issue Type

- Bug Report

# Ansible, Collection, Controller details

tried all version.
ansible.controller 4.5.1

```console (paste below)
ansible --version

ansible-galaxy collection list

Controller version

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

RHEL 8

# Desired Behavior

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)

```

# STEPS TO REPRODUCE

You can use the roles and try to create any job template and change its verbosity back and forth between 0 and other values

**Comment by djdanielsson** [comment]
we can look into this but it is very likely an issue with the module, have you tried the latest awx.awx collection?

**Comment by gokulan-g** [comment]
We use ansible.controller collection which is officially supported by Redhat. Initially I raised a case with redhat using my corporate account and was told to raise a issue here as it is not the problem with the collection. I have tested this on many versions of ansible.controller and this issue persists. Seems to be the problem with the role. Would appreciate any help on this

**Comment by gokulan-g** [comment]
Case number: 03752193

**Comment by djdanielsson** [comment]
I have confirmed it does appear to be a bug in the role, we will try and figure out the cause of it and create a solution once the issue is found. If anyone else has time to help figure out the cause and post it here that would be great.

**Comment by djdanielsson** [comment]
ok I figured it out, until we can merge this fix and do a release (unless you pull the collection directly from GitHub) a way to work around it would be to quote it "0"

**Comment by gokulan-g** [comment]
It worked Thanks a mill.

May I ask, is there a way to print the extra_vars of a job templates and variables of inventories that we receive via api in yml format, which then can be given as input to these roles to build them back. I'm having trouble arranging these extra_vars and varibles in yml format, especially when they have variables like {{ something }} as there data. Manually i can use !unsafe and get it built, but i looking for an automated way to writes these extra_vars or variables in yml file. I would truly appreciate you help on this
