### ISSUE TITLE
Release pipeline fails - versions 2.8.x not available in galaxy

### ISSUE THREAD

**Issue by bogdanmuresan** [redhat-cop/automate_tower_genie_collections#837]
# Summary

The release pipeline fails:
https://github.com/redhat-cop/controller_configuration/actions/workflows/release.yml

and therefore latest version available in galaxy is 2.7.1

https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/

# Issue Type

- Bug Report

**Comment by djdanielsson** [comment]
yes we know and are working on it #835
