### ISSUE TITLE
tower_credential should validate for credential_type based on module expectations

### ISSUE THREAD

**Issue by mpetrive-rh** [redhat-cop/automate_tower_genie_collections#88]

**Comment by sean-m-sullivan** [comment]
Testing needs to be done to figure out if its Machines or machine is accepted by tower, and to then normalize user data if possible to match if they spell the word correctly but not in right form.

**Comment by mpetrive-rh** [comment]
No easy way to resolve this since users can create custom credential types with any name.  Utilize reference documentation
