### ISSUE TITLE
Inconsistent variable name used for role secure logging

### ISSUE THREAD

**Issue by myllynen** [redhat-cop/automate_tower_genie_collections#895]
## Summary

In `roles/roles/meta/argument_specs.yml` variable `controller_configuration_roles_secure_logging` is listed but elsewhere in the `roles` role `controller_configuration_role_secure_logging` is used so most likely `roles/roles/meta/argument_specs.yml` should be fixed.

**Comment by djdanielsson** [comment]
PR's welcome
