### ISSUE TITLE
API JSON don't contain information about sourced credentials

### ISSUE THREAD

**Issue by skynetmo** [redhat-cop/automate_tower_genie_collections#897]
Hello, 

i was implementing a playbook to get the list of sourced credentials from another credentials under AAP , but on the JSON i don't have any information that indicate those credentials are sourced from CyberArk for example . the inputs field on the JSON response is empty .
is there a field on the JSON that give me details about the credential ? also is it possible to use controller_configuration collection to get this information ?

Thank you in advance,

**Comment by sean-m-sullivan** [comment]
You are correct there is no information from the controller application about sourced credentials under the specific credential. Which Json are you referring to, an export, or your config?

The credential API has it under api/v2/credentials/#/input_sources or api/v2/credential_input_sources/#

There is no indication that one is managed by the other in the config, and they have a relation in the database/api to each other

**Comment by mondherGL** [comment]
Hello , 

is there a way to get credentials informations using controller_configuration collection , for axample all credentials name and all credential_input_sources related to a credential  ?
