### ISSUE TITLE
Auto merge of changelog failed

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/automate_tower_genie_collections#90]
Two problems here:

1. When the changelog PR is raised automatically, it gets labelled which should kick off the auto merge action. It does not.
2. The auto-merge action fails because it requires an approval

We can proceed with this in two ways:
1. we try to work out the cause of the action not starting on initial labelling (by removing the label and re-adding it does start the action). We then need to find a way of auto-approving the PR as well.
2. We just raise the one of the maintainers can just approve and merge it manually.

**Comment by sean-m-sullivan** [comment]
Github has rebuffed our efforts here, closing.
