### ISSUE TITLE
meta_dependency_check bug: One of awx.awx or ansible.controller must be installed

### ISSUE THREAD

**Issue by przemkalit** [redhat-cop/automate_tower_genie_collections#917]
## Summary

I've notice that `meta_dependency_check` is breaking usage of the collection. This is the output using the command of this role:
```bash
ansible-galaxy collection verify ansible.controller
ERROR! Error when getting collection version metadata for ansible.controller:4.5.6 from default (https://galaxy.ansible.com/api/) (HTTP Code: 404, Message: Not found. Code: not_found)
```

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

```console (paste below)

ansible-galaxy collection list

# /home/runner/.ansible/collections/ansible_collections
Collection                     Version
------------------------------ -------
ansible.controller             4.5.7  
infra.controller_configuration 2.10.3 
```

- ansible installation EE

## OS / ENVIRONMENT

RH9

## Desired Behavior

Collection ansible.controller is properly identified.

## Actual Behavior

Collection cannot be used due the error:
```console (error)
One of awx.awx or ansible.controller must be installed
```

## STEPS TO REPRODUCE

1. Download collections to Private Automation Hub.
2. Execute playbook that use collection.

**Comment by ffirg** [comment]
I was testing this with ansible.controller 4.6.0 yesterday, which is required for AAP 2.5 support and that is affected by this bug as well.

**Comment by ffirg** [comment]
Also note that awx.awx will no longer work with AAP 2.5 so it might be a good idea to make this clearer in the output at the same time

**Comment by djdanielsson** [comment]
I will look into this, thanks for reporting it.

**Comment by przemkalit** [comment]
Okay, FYI we discovered on our side that we were missing a configuration file for ansible-galaxy inside the EE, but I think the collection should allow to use offline mode for this verification.

**Comment by przemkalit** [comment]
@djdanielsson We would like to request possibility to disable certificate checks during the verification of the collection.

**Comment by djdanielsson** [comment]
That should be managed by ansible.cfg

**Comment by przemkalit** [comment]
Ah, yes I am blind `GALAXY_IGNORE_CERTS`, thanks.

**Comment by djdanielsson** [comment]
seems like this ended up not being an issue so closing
