### ISSUE TITLE
`infra.aap_configuration.controller_credentials` role does not allow for setting the `request_timeout` parameter

### ISSUE THREAD

**Issue by demonpig** [redhat-cop/automate_tower_genie_collections#936]
## Summary

The `infra.aap_configuration.controller_credentials` role does not allow for setting the `request_timeout` parameter. This means that the default of 10 seconds will be used when the `credential` (from within `awx.awx` collection) is called.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

N/A

## OS / ENVIRONMENT

N/A

## Desired Behavior

Allow for setting the `request_timeout` parameter for this particular role as its done within the other controller-related roles.

## Actual Behavior

MISSING

- [infra.aap_configuration.credentials](https://github.com/redhat-cop/infra.aap_configuration/blob/devel/roles/controller_credentials/tasks/main.yml#L16C1-L22C86) role specific variables section

PRESENT

- [infra.aap_configuration.controller_credential_types](https://github.com/redhat-cop/infra.aap_configuration/blob/devel/roles/controller_credential_types/tasks/main.yml#L12-L19) role specific variables section

- [infra.aap_configuration.controller_applications](https://github.com/redhat-cop/infra.aap_configuration/blob/devel/roles/controller_applications/tasks/main.yml#L15-L22) role specific variables section

## STEPS TO REPRODUCE

Still need to work on this. Above is just what I had observed when looking through the collection's code.

**Comment by sean-m-sullivan** [comment]
Noted, I've fixed it in our latest rewrite, but we may need to backport this.
