### ISSUE TITLE
Missing support for gateway_role_team_assignments

### ISSUE THREAD

**Issue by bogdanmuresan** [redhat-cop/automate_tower_genie_collections#989]
## Summary

Cannot add role_team_assignment

https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/role_team_assignment.py

## Issue Type

- Bug Report

**Comment by bogdanmuresan** [comment]
I have also opened a support ticket to RedHat to add it to ansible.platform (https://access.redhat.com/support/cases/#/case/03999294).

**Comment by bogdanmuresan** [comment]
Are gateway_role_team_assignments even used in 2.5? Or is it still work in progress? Are we supposed to use the controller_roles module to manage teams RBAC, and role_user_assignment to manage user RBAC? It is getting a bit confusing...

**Comment by djdanielsson** [comment]
I am not positive, I have not had much time to spend on RBAC with 2.5, but I agree it seems confusing.

**Comment by bogdanmuresan** [comment]
It looks like that using the controller_role still works, and I was able to grant "JobTemplate Execute" to a team on a job template using that.

One issue is "controller_roles" is missing from controller_configuration_dispatcher_roles - I am not sure if I should add it, or there will be another way of granting permissions to execute a job template to a team..

Just in case, here is a PR to add it: https://github.com/redhat-cop/infra.aap_configuration/pull/995/files

The gateway_authenticator_maps as Sean suggested does not have this functionality. When selecting map_type: role, the only roles available are: Organization Admin, Organization Member, Platform Auditor, Team Admin and Team Member.
