### ISSUE TITLE
No consistency between `README.md` and `defaults/main.yml` in `controller_credentials` role

### ISSUE THREAD

**Issue by akira6592** [redhat-cop/automate_tower_genie_collections#990]
## Summary

The default value of `controller_configuration_credentials_secure_logging` in [`controller_credentials/defaults/main.yml`](https://github.com/redhat-cop/infra.aap_configuration/blob/3.1.0/roles/controller_credentials/defaults/main.yml#L4) is `"{{ aap_configuration_secure_logging | default(true) }}"`.

But [`README.md`](https://github.com/redhat-cop/infra.aap_configuration/tree/3.1.0/roles/controller_credentials#secure-logging-variables) says default is `false`.

Which is correct?

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

N/A (Document only)

## OS / ENVIRONMENT

N/A (Document only)

## Desired Behavior

N/A (Document only)

## Actual Behavior

N/A (Document only)

## STEPS TO REPRODUCE
N/A (Document only)

**Comment by djdanielsson** [comment]
for credentials it is default true, I think there might be one other role that defaults true but the rest are false which is probably why it is wrong in the readme.

**Comment by akira6592** [comment]
Thank you. I think so, too.

There is same problem in the `eda_credentials` role.

Because the `*_credentials` role treats  a sensitive data, I think `true` is appropriate the default for `*_credentials_secure_logging`.

I'll submit a PR for fixing.
