### ISSUE TITLE
controller_lables says organization is optional, but task shows as required

### ISSUE THREAD

**Issue by MallocArray** [redhat-cop/automate_tower_genie_collections#999]
## Summary

infra.aap_configuration.controller_labels shows in the README under Data Structure that `organization` is not required.
![image](https://github.com/user-attachments/assets/18e273e0-60bf-4b88-acbe-980868a33945)

When running this against AWX 24.6.1 with just a list of names, it fails
`FAILED! => {"msg": "Mandatory variable 'organization'  not defined."}`

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.16.13]
  config file = /runner/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /runner/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
ansible-galaxy collection list
awx.awx                   24.6.1 
infra.aap_configuration   3.1.0  

Controller version
AWX 24.6.1
```

- ansible installation method: one of source, pip, OS package, EE
EE

## Desired Behavior

A datastructure with only a list of names of labels will result in Labels being added to AWX
## Actual Behavior

Task failed because the organization was not set

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)
TASK [infra.aap_configuration.controller_labels : Managing Labels] *******************************************************************************************************
fatal: [awx.domain.com]: FAILED! => {"msg": "Mandatory variable 'organization'  not defined."}
```

## STEPS TO REPRODUCE

```yaml (playbook/task)

```

```yaml (config/list/array/variables)
controller_labels:
  - name: activedirectory
  - name: awx
  - name: azure
```

**Comment by djdanielsson** [comment]
it does appear they updated the module to require this now so thanks for making the documentation match
